### ISSUE TITLE
Include AWS Compute Optimizer data in the CUDOS dashboard

### ISSUE THREAD

**Issue by nhammadi** [aws-samples/aws-cudos-framework-deployment#104]
AWS Compute optimizer provide a really good suggestions to save costs in AWS. May be include this data also in one of the dashboards will be handy specially the service provide the necessary APIs to automate data export to S3

**Comment by megareez** [comment]
for data collection we already have this: https://www.wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/

dashboard itself is in the roadmap
