### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by martinfelts** [aws-samples/aws-cudos-framework-deployment#112]
I am getting errors on multiple steps of the deployment.

I had the previous framework fully deployed and I tried to run the update but it was not successful.

I then decided to just run the delete commands and cleanup commands and start fresh however it is not clear to me if I need to clone the repo or is it being pulled from Git.

I decided to clone the repo with the legacy script and then attempt the deployment from there and I received and error yet again.

![image](https://user-images.githubusercontent.com/51484290/145496524-1f01843d-d683-4655-af46-0ecb6badcea8.png)

I have attached a screen shot of the error.

**Comment by ersil** [comment]
I see the same error. (with a CID dashboard deployment).

**Comment by darken99** [comment]
Please read README, it covers compatibility and has usage instructions
