### ISSUE TITLE
Error in ListUsers operation when deploying dashboard to a different region than QuickSight Identity Region

### ISSUE THREAD

**Issue by AWSbrendmb** [aws-samples/aws-cudos-framework-deployment#12]
When executing "./shell-script/customer-cudos.sh deploy-datasets" I received the following error.

An error occurred (AccessDeniedException) when calling the ListUsers operation: Operation is being called from endpoint us-west-2, but your identity region is us-east-1. Please use the us-east-1 endpoint.

I was able to overcome the error by editing common.sh and specifying us-east-1 in the "aws quicksight list-users" command.  I have created a pull request that adds an additional parameter for this use case.

**Comment by darken99** [comment]
Fixed by #11 and #13
