### ISSUE TITLE
Legacy - Updating dashboard errors

### ISSUE THREAD

**Issue by james-lukensow** [aws-samples/aws-cudos-framework-deployment#122]
We're using the so-called "Legacy" deployment method. The commit hash is `72de39d` (https://github.com/aws-samples/aws-cudos-framework-deployment/tree/72de39dee813a24e039ed391e37819819bb3acd2) 

Issue:

**Cudos** - The uploaded version reports back as undefined, and an upgrade always executes regardless of what version is currently deployed. I believe the error lies around: https://github.com/aws-samples/aws-cudos-framework-deployment/blob/72de39dee813a24e039ed391e37819819bb3acd2/cudos/shell-script/customer-cudos.sh#L159. I would expect an upgrade to only execute when the source version is higher than the deployed version.

**Trends** - This fails when attempting to upgrade the trends dashboard. Due to the version not being returned, you will get an error when comparing the current dashboard source version to the live deployed version. https://github.com/aws-samples/aws-cudos-framework-deployment/blob/72de39dee813a24e039ed391e37819819bb3acd2/trends/shell-script/trends.sh#L163. I ran the command manually to see what version was being returned from the cli. 

`aws quicksight describe-dashboard --dashboard-id $dashboardId --query 'Dashboard.Version.SourceEntityArn' \
        --aws-account-id $account | cut -f 6 -d \: | cut -f 4 -d \/)`

If you remove the second "cut", you'll get a partial text match. However, add it back in and you'll get an empty response.

**Comment by darken99** [comment]
Please use the latest tool instead, bash support is EOL.
