### ISSUE TITLE
cid-cmd account mapping fails in every scenario

### ISSUE THREAD

**Issue by cristian-popa** [aws-samples/aws-cudos-framework-deployment#129]
Customer has one account with a quote in it (payer account) .
Account map with organization option is failing if there is an account with single quotes in it. I think the account name should be sql escaped here: https://github.com/aws-samples/aws-cudos-framework-deployment/blob/bb0b4544ee11bf6ed94b08b0b3778cee47247fea/cid/helpers/account_map.py#L280 
account-map with csv option fails because it cannot find acct-metadata table in athena
dummy account map is not working, simply saying it found 0 rows and reprompting for account mapping option.

**Comment by darken99** [comment]
This should be fixed in version 0.1.7
