### ISSUE TITLE
Error while deploying second dashboard in the same account

### ISSUE THREAD

**Issue by omkargokhale18** [aws-samples/aws-cudos-framework-deployment#197]
There is already a CUDOS dashboard created with Payer Account A. and now trying to deploy another one with payer account B. Getting errors with dataset creation. 

Error from the output snippet: 
There are still 5 datasets missing: compute_savings_plan_eligible_spend, customer_all, ec2_running_cost, s3_view, summary_view
? Select AWS Athena database to use **********
DataSet "compute_savings_plan_eligible_spend" creation created
Creating dataset: customer_all...Checking if CUR is enabled and available...
        Athena table: awsbilling_athena
        Resource IDs: yes
        SavingsPlans: no
        Reserved Instances: no
done
DataSet "customer_all" creation created
Creating dataset: ec2_running_cost...DataSet "ec2_running_cost" creation created
Creating dataset: s3_view...DataSet "s3_view" creation created
Creating dataset: summary_view...DataSet "summary_view" creation created
Looking for local overrides file "work/**********/cudos.json"...not found
Latest template: arn:aws:quicksight:us-east-1:223485597511:template/cudos_dashboard_v3/version/163

Deploying...failed, dumping error message
"Parameter validation failed:\nInvalid length for parameter SourceEntity.SourceTemplate.DataSetReferences, value: 0, valid min length: 1"
Deleting dashboard...not found

**Comment by iakov-aws** [comment]
This was fixed with one of previous releases. Please update and retry. Feel free to reopen issue if still relevant
