### ISSUE TITLE
Error deploying tao.cfn.yml when providing a taoSuffix

### ISSUE THREAD

**Issue by james-lukensow** [aws-samples/aws-cudos-framework-deployment#212]
On the latest release (8fb0fd4) when deploying the TAO dashboard and providing a taoSuffix, an error will be thrown stating that the Athena table (ta_organizational_view_reports-${suffix}" does not exist.

By updating the following line, I'm able to deploy the dashboard and still provide a suffix.

**Original**
https://github.com/aws-samples/aws-cudos-framework-deployment/blob/8fb0fd4253b9b58df854b91387318db08c496572/cfn-templates/tao.cfn.yml#L531

**Updated**
```
Name: !FindInMap ["Definitions", "taoAthenaTable", "Value"]
```

What I'm noticing, is that the suffix is used correctly in the cloud formation file, except for when creating the Athena data source. Now, this could be okay, but later on, when creating the QS Datasource, the table is hardcoded without the prefix.

```
PhysicalTableMap:
        b5de237f-b599-407f-87ec-32024624ba65:
          RelationalTable:
            DataSourceArn: !GetAtt taoQuickSightDataSource.Arn
            Catalog: AwsDataCatalog
            Schema: !Ref DatabaseName
            Name: ta_organizational_view_reports
            InputColumns:
              !FindInMap ["References", "taoDataSetInputColumns", "Value"]
```

**Comment by iakov-aws** [comment]
Fix was merged to the main branch. Thank you.
