### ISSUE TITLE
Incorrect output of suffix when deploying cudos cfn

### ISSUE THREAD

**Issue by james-lukensow** [aws-samples/aws-cudos-framework-deployment#221]
On the latest release (0.1.17 and 0.1.16), when you provide a suffix for cudos-cfn.yml, the output value is incorrect.

Input:

`-96e8612`

Output

`_--96e8612`

As a result of this, when deploying (spice-refresh-cfn.yml), the refresh will not run because of an incorrect naming of the QS Datasets and the Spice Refresh uses `_--96e8612` as part of the Lambda function name. Where ideally, it should be `-96e8612`.

[Value: !Join [ "-" , [ "_",!Ref Suffix ] ]](https://github.com/aws-samples/aws-cudos-framework-deployment/blob/7ca92c4ab1706c7c3987feda95b862348527893c/cfn-templates/cudos-cfn.yml#L2135)

**Comment by iakov-aws** [comment]
This https://github.com/aws-samples/aws-cudos-framework-deployment/pull/223 was fixed so i assume the issue is fixed as well. Please reopen if not, and thanks for the fix contribution!
