### ISSUE TITLE
Unable to deploy kpi-cfn.yml after cudos-cfn.yml

### ISSUE THREAD

**Issue by james-lukensow** [aws-samples/aws-cudos-framework-deployment#227]
I'm getting an error [0.1.17](https://github.com/aws-samples/aws-cudos-framework-deployment/releases/tag/0.1.17) when trying to deploy kpi-cfn.yml after deploying the cudos formation template.

```
xxxxx|SummaryView already exists in stack arn:aws:cloudformation:us-west-2:xxxxxx:stack/MoCudos/6644b8e0-b6ad-11ec-afb4-06fe22b95cfd
```

I assumed the KPI cloud formation template can be deployed alongside the cudos stack.

**Comment by iakov-aws** [comment]
Yes, currently it is difficult to mange multiple cost related dashboards  via CFN. We are working on a solution. Please use cid-cmd tool to manage dashboards as a fallback solution.

**Comment by mubarak-j** [comment]
Does this limitation still apply in current version?

**Comment by iakov-aws** [comment]
Yes.  This requires a complete refactoring of cfn. 

Please use cid-cmd tool in the command line.

**Comment by iakov-aws** [comment]
Here a new CFN that allows you to deploy all dashboards in one run: 
https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/cfn-templates/cid-cfn.yml
