### ISSUE TITLE
summary_view.sql query fails to execute if the customer does not have RDS usage

### ISSUE THREAD

**Issue by AWSbrendmb** [aws-samples/aws-cudos-framework-deployment#23]
Results in :
work/############/views/summary_view.sql
####### Executed query id: c656d970-XXXX-XXXX-XXXX-b254XXXX7129, status: FAILED

Your query has the following error(s):
SYNTAX_ERROR: line 45:4: Column 'product_database_engine' cannot be resolved

Multiple possible solutions:
1) Check for this situation in the AwsDataCatalog.information_schema.columns and choose the appropriate CREATE VIEW sql query depending on customer situation.
2) Prompt user if they have usage and choose the appropriate CREATE VIEW sql query based on their choice

**Comment by megareez** [comment]
Mitigation: Spin up an RDS Free Tier instance for an hour to provision the required CUR columns.
