### ISSUE TITLE
 ERROR - cid.helpers.athena:execute_query:187 

### ISSUE THREAD

**Issue by AlbertoMijares** [aws-samples/aws-cudos-framework-deployment#246]
I have CUDOS and Cost Intelligence dashboards installed with Cloudformation.

Error installing the KPI dashboard with CLI.

[KPI_dashbard_debug.txt](https://github.com/aws-samples/aws-cudos-framework-deployment/files/8617351/KPI_dashbard_debug.txt)

**Comment by darken99** [comment]
KPI Dashboard requires few products billing history, including RDS, Elasticache
This is not a tool bug, but should be covered in the LAB
