### ISSUE TITLE
CRITICAL - cid.helpers.quicksight:describe_template:671 - AWS QuickSight Enterprise Edition is required

### ISSUE THREAD

**Issue by vstanimirovic** [aws-samples/aws-cudos-framework-deployment#272]
I was using version cid-cmd-0.1.22 and getting the error:

Error: Template cudos_dashboard_v3 is not available in account 223485597511

Then i ran:

pip3 install --upgrade cid-cmd

and upgraded to cid-cmd-0.1.28

Now when i run

cid-cmd deploy 

and choose to deploy cudos i am getting the follwoing error:

CRITICAL - cid.helpers.quicksight:describe_template:671 - AWS QuickSight Enterprise Edition is required

Is it correct that i need AWS QuickSight Enterprise Edition?

**Comment by iakov-aws** [comment]
Yes. Enterprise Edition is needed for automation. Please check readme https://github.com/aws-samples/aws-cudos-framework-deployment/#before-you-start
