### ISSUE TITLE
Multiple Payer Account

### ISSUE THREAD

**Issue by shahbour** [aws-samples/aws-cudos-framework-deployment#279]
I am trying to deploy CUDOS with multiple [payer accounts](https://catalog.us-east-1.prod.workshops.aws/workshops/fd889151-38aa-4fe2-a29d-d5fa557197bb/en-US/prerequisites-multipayer)  , all good but it is creating multiple tables in Athena , one for each .

When using cid-cmd deploy I have to choose only one table 

```
Multiple CUR tables found, please select one
```

Should the crawler insert the data in one table or i can adjust the view to read from multiple tables ?

**Comment by lkhomenk** [comment]
@shahbour have you managed to resolve this?
