### ISSUE TITLE
Can't deploy COD dashboard due to restricted access to management account

### ISSUE THREAD

**Issue by SerhiiSokolov** [aws-samples/aws-cudos-framework-deployment#283]
I use 0.1.29 version and try to deploy COD dashboard.
Dashboard deploy is performed in sandbox account which is a part of AWS organization and it's not possible to get access to management account. 

> cid-cmd deploy

command fails with error
```
? [dashboard-id] Please select dashboard to install: [compute-optimizer-dashboard] Compute Optimizer Dashboard
Discovering deployed dashboards...  [------------------------------------]    0%  None

Required datasets: 
 - compute_optimizer_all_options

2022-06-13 21:32:18,984 - CRITICAL - cid.helpers.quicksight:describe_template:678 - Error: An error occurred (AccessDeniedException) when calling the DescribeTemplate operation: User: arn:aws:sts::******:assumed-role/********* is not authorized to perform: quicksight:DescribeTemplate on resource: arn:aws:quicksight:us-east-1:*******:template/compute_optimizer with an explicit deny in a service control policy - Cannot find compute_optimizer in account *******.
```

**Comment by iakov-aws** [comment]
Hello, 
The error message indicates that the restriction comes from SCP. Most probably this SCP limit access to region where the template is deployed. 

For now we only deploy template in us-east-1 region.

**Comment by SerhiiSokolov** [comment]
I did not know that only us-east-1 supported. Anyway  arn:aws:quicksight:us-east-1:*******:template/compute_optimizer here account ID is master account of organisation.

**Comment by iakov-aws** [comment]
You can install in any region but the template is in us-east-1 

in your case your organization limit usage of us-east-1 by AWS SCP ( https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html )


You can ask an exemption of your data collection acc for the install time.
