### ISSUE TITLE
Issues deploy cid_cudos.yaml with QSCURBuildViewsLambdaExecutor resource

### ISSUE THREAD

**Issue by gcaride** [aws-samples/aws-cudos-framework-deployment#288]
Hi, 

I'm currently having an issue deploying the [CUDOS CloudFormation stack](https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/2b_cudos_dashboard/#option-3-cloudformation-deployment). 

Prerequisites are done.

1. Created the AWS Cost and Usage Reports
2. Created the references for the new Athena Workgroup
3. Run the crawler-cfn.yml
4. Created Quicksight account

Then I run the [CUDOS CloudFormation stack](https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/2b_cudos_dashboard/#option-3-cloudformation-deployment). 

I receive this error:
![image](https://user-images.githubusercontent.com/83322276/175362581-b78bc23c-088a-4cf8-833c-60be8e4752e9.png)

Looking the logs I didn't saw any error related to permissions, or some misconfiguration. I have attached the log from Cloudwatch Log Group in `.csv` format.

[log-events-viewer-result.csv](https://github.com/aws-samples/aws-cudos-framework-deployment/files/8969581/log-events-viewer-result.csv)

Aditional info: 

- I have files on the bucket i created:

![image](https://user-images.githubusercontent.com/83322276/175363162-2315c7aa-bdab-46cd-bc57-2c8257bda440.png)

- When i runned the CloudFormation stack in the `AthenaQueryResultsBucket` created two files

![image](https://user-images.githubusercontent.com/83322276/175363380-869b5d66-0336-4b39-9e95-767ee51f9251.png)

- Confirm in Glue Tables are created:
![image](https://user-images.githubusercontent.com/83322276/175363865-2b0e195d-0be4-4592-9c03-9ce39c803601.png)

Any other information required, I am at your disposal.

Thanks!!

Regards.

**Comment by iakov-aws** [comment]
Looks it was not possible to execute Athena query. 

Please check that you set up a result bucket in primary workgroup in Athena.

Alternatively you can try command line method it will give you more verbose output

**Comment by iakov-aws** [comment]
Also please check if your cur is populated and you run a CFN for creating a crawler for this cur.

**Comment by iakov-aws** [comment]
No update. Closing. Please reopen if still relevant
