### ISSUE TITLE
update-dashboard bug

### ISSUE THREAD

**Issue by sandwormusmc** [aws-samples/aws-cudos-framework-deployment#29]
```[cloudshell-user@ip-10-0-18-186 cudos]$ ./shell-script/customer-cudos.sh update-dashboard
Checking environment
AWS CLI version...2.1.28...ok
Fetching AWS Account ID...ok

Config file detected work/xxx/config:
----
export region=us-west-2
export aws_identity_region=us-west-2
export aws_qs_identity_region=us-west-2
export athena_database_name=athenacurcfn_myfirstcur
export athena_cur_table_name=myfirstcur
export user_arn=arn:aws:quicksight:us-west-2:xxx:user/default/Matt
export AWS_DEFAULT_REGION=us-west-2
----
Checking for updates...
Getting latest available source template version...latest available template version is 98
Getting currently deployed source version...latest available template version is None
./shell-script/customer-cudos.sh: line 178: [: None: integer expression expected
./shell-script/customer-cudos.sh: line 181: [: None: integer expression expected
Update available ( None > 98 ), proceeding
...
```

Running with bash -x:

```latest available template version is None
+ '[' None -eq 98 ']'
./shell-script/customer-cudos.sh: line 178: [: None: integer expression expected
+ '[' None -gt 98 ']'
./shell-script/customer-cudos.sh: line 181: [: None: integer expression expected
+ echo 'Update available ( None > 98 ), proceeding'

**Comment by darken99** [comment]
Seems like you never deployed the dashboard

**Comment by megareez** [comment]
No, there is a bug that API for QuickSight in US-EAST-1 returns the value for SourceEntityARN and some other regions don't.

**Comment by JamieB101** [comment]
i'm also facing the same issue;
`[cloudshell-user@ip-10-0-49-89 cudos]$ ./shell-script/customer-cudos.sh update-dashboard
Checking environment
AWS CLI version...2.1.28...ok
Fetching AWS Account ID...ok

  Config file detected work/199744280866/config:
----
export region=eu-west-1
export aws_identity_region=us-east-1
export aws_qs_identity_region=us-east-1
export athena_database_name=athenacurcfn_c_u_d_o_sv2
export athena_cur_table_name=cudosv2
export user_arn=arn:aws:quicksight:us-east-1:199744280866:user/default/AWS_DUB_ROL_OrgAdminAccess_protected/Jamie.Banks@edfenergy.com
export AWS_DEFAULT_REGION=eu-west-1
----
Checking for updates...
Getting latest available source template version...latest available template version is 103
Getting currently deployed source version...latest available template version is None
./shell-script/customer-cudos.sh: line 178: [: None: integer expression expected
./shell-script/customer-cudos.sh: line 181: [: None: integer expression expected
Update available ( None > 103 ), proceeding

####### Pulling latest changes...


####### Applying latest changes to the deployed Dashboard...

Error: something went wrong, exiting`

**Comment by megareez** [comment]
Has been fixed, please redeploy the dashboard to make use of the newly populated field SourceEntityArn, update should work as expected after redeploy
