### ISSUE TITLE
Column 'product_database_engine' cannot be resolved

### ISSUE THREAD

**Issue by michaelpegg** [aws-samples/aws-cudos-framework-deployment#311]
Hi,

I am trying to deploy the CUDOS dashboard and am hitting the following error where it cannot deploy the summary_view but it successfully deploys the 3 other required views.

I cannot see any errors in the cur, s3, iam, glue, athena or quicksight configs.

`Missing views: summary_view
2022-08-04 10:04:43,239 - ERROR - cid.helpers.athena:execute_query:236 - Athena query failed: line 47:4: Column 'product_database_engine' cannot be resolved
2022-08-04 10:04:43,250 - ERROR - cid.helpers.athena:execute_query:237 - Failure reason: line 47:4 Column 'product_database_engine' cannot be resolved`

I have followed the prerequisites as described here: https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1_prerequistes/

**Comment by darken99** [comment]
This is a known limitation described [here](https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/faq/#how-do-i-fix-the-product_cache_engine-cannot-be-resolved-error)

**Comment by darken99** [comment]
Duplicate: #45

**Comment by michaelpegg** [comment]
does it not make sense to add this to the prerequisites?
