### ISSUE TITLE
s3 bucket permission error

### ISSUE THREAD

**Issue by michaelpegg** [aws-samples/aws-cudos-framework-deployment#315]
Hi,

I am seeing the following error:
![image](https://user-images.githubusercontent.com/94115077/183043552-04460754-c8df-4085-a3e9-b3b1b0030cfc.png)

I have added the athena service but still see the same error.

my s3 permissions are:
![image](https://user-images.githubusercontent.com/94115077/183048139-a57b63e9-8a5d-47ef-aeeb-1b402f166898.png)

Can you advise what s3 bucket permissions are required?

**Comment by darken99** [comment]
This is covered in deployment guide's [pre-requisites section](https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1_prerequistes/#enable-quicksight)
