### ISSUE TITLE
Using "Test Data" and CUDOS deployed via Cloudformation shows "No Data"

### ISSUE THREAD

**Issue by ghost** [aws-samples/aws-cudos-framework-deployment#344]
Hello!

I am following the workshop: https://dx1572sre29wk.cloudfront.net/cost/200_labs/200_cloud_intelligence/

I have set this up using test data however now that it is deployed via cloudformation my dashboards show no data. 

![image](https://user-images.githubusercontent.com/42644299/186701614-69ef702d-b07f-4799-8101-d720ca4d6372.png)

I am able to query the data in athena and customerall (one of the CF deployed datasets) dataset is showing the data.

![image](https://user-images.githubusercontent.com/42644299/186701760-7f12329d-0e4c-40fe-a5be-e1193926c310.png)
 
I think there is an issue with the spice datasets. 

![image](https://user-images.githubusercontent.com/42644299/186702298-f895ac9a-813a-4002-a451-3450ccc1817d.png)

I remember there was previously an issue with not having RDS run before in the account so I've deployed a database to test that.

**Comment by iakov-aws** [comment]
What happens if you query summary view in athena?

> SELECT * FROM summary_view LIMIT 10;

**Comment by iakov-aws** [comment]
Please reopen if still an issue
