### ISSUE TITLE
multi-payer - multiple tables instead of one aggregated?

### ISSUE THREAD

**Issue by michaelpegg** [aws-samples/aws-cudos-framework-deployment#367]
I have deployed a multi-payer setup with S3 replicating two accounts CUR data.

I get prompted to select which CUR Table: 
![image](https://user-images.githubusercontent.com/94115077/190387400-2cf8554b-cee7-45ac-b5fd-f51e05849054.png)

I can see the multiple tables in Glue:
![image](https://user-images.githubusercontent.com/94115077/190387553-85d08c8c-4e71-4c3b-95b3-b683a3520b5a.png)

I assume this is from the multi-payer data not being merged somehow?
Can you advise how to rectify?

**Comment by aloeveraao** [comment]
I am having the same issue. I deployed the dashboard with just 1 account originally, and replicated the second account afterwards. 

Following the lab, the crawler created a second table for the second account in the same Athena DB as the first account. The only way I can figure out to make it work is to UNION join the two tables in the Athena view queries. I emailed the CUDOS email address listed in the lab and all they said was that there's only supposed to be one table...

My crawler setup is identical to what they say to do in the lab so I'm not sure where to go from here.

**Comment by iakov-aws** [comment]
We are working on a new CFN for replication configuration:
- CFN; https://github.com/awslabs/aws-well-architected-labs/blob/fcf03ac6c05d772c6f0dcd92459837aadb0f49b0/static/Cost/200_Cloud_Intelligence/templates/cur-aggregation/cur-aggregation.yaml
- DOC: https://github.com/awslabs/aws-well-architected-labs/blob/fcf03ac6c05d772c6f0dcd92459837aadb0f49b0/content/Cost/200_Labs/200_Cloud_Intelligence/FAQ/_index.md

it will be merged to our main documentation in the following weeks you can use that or just align to crawler configuration you can find in the CFN

**Comment by michaelpegg** [comment]
gave this a go.

had to comment out the analytics section due to s3 bucket permissions or the code would error.
I couldn't get it to deploy the local s3 bucket, unsure why. Maybe the expectation is that you create that manually? not sure how this would work cross-account otherwise?

is there expectation this will enable multi-payer aggregation to function?

As far as I can see from the code the data is:
replicated from the bucket -local to the bucket -shared/cost-usage-reports/AccountId
then the glue crawler is looking at -shared/cost-usage-reports/

I assume this would still generate 1 set of tables per AccountId subfolder?

**Comment by iakov-aws** [comment]
please check the cfn for multi account. This was relaesed some time agohttps://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1a_cur_setup/
