### ISSUE TITLE
CUDOS cur_new.json missing resource_tags_user_project

### ISSUE THREAD

**Issue by guelah75** [aws-samples/aws-cudos-framework-deployment#37]
I believe we may be missing some resource_tags_user_* tags from the cudos_cur dataset creation. Looks like at least resource_tags_user_project is missing from the json in  aws-cudos-framework-deployment/cudos/dataset-templates/cur_new.json 

I believe this may cause issues when customers attempt to populate the Tagsplorer portion of the dashbaord if they are looking for 'project' tag

**Comment by guelah75** [comment]
after investigating further, perhaps what is really needed is a way to query the user created tags and populate the cur_new.json file with all customer created tags to ensure they are all included in the QuickSight dashboards.

**Comment by yprikhodko** [comment]
Tag fields are populated by Glue crawler to Athena table. To get them appear in cudos_cur dataset the only thing is needed is to open dataset in QuickSight and save it. Once done all tag fields will be available in analysis to be used in Tagsplorer
