### ISSUE TITLE
Allow updating accounts IDs mapping when using csv file

### ISSUE THREAD

**Issue by mubarak-j** [aws-samples/aws-cudos-framework-deployment#372]
I opted for import accounts ID using csv file when creating the dashboards via cid-cmd. But I couldn't find a way to update/add news accounts when I used `cid-cmd update --force`. Is it possible to add a prompt for csv file when rthe unning update?

Is there a possible workaround for this? 

Edit: also kindly consider helping the community with your expertise in the [discussions](https://github.com/aws-samples/aws-cudos-framework-deployment/discussions) section :)

**Comment by iakov-aws** [comment]
the `cid-cmd map` command with CSV parameter is more for a one shot. If you need to update it, please rather upload csv to S3 and set up a crawler to get updated table. 

Or even better set up this lab to get the map automaticaly https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/ 

also updating account mapping with csv should work for update as well so i do not see the issue

**Comment by mubarak-j** [comment]
@darken99 @iakov-aws the issue is that providing csv file is supported during the initial deployment `cid-cmd deploy`. But if I want to update the dashboards with new accounts, using `cid-cmd update --force` doesn't prompt for providing an updated csv/account map file.

**Comment by darken99** [comment]
You can use `cid-cmd map` to update mapping
