### ISSUE TITLE
Workshop URLs redirect to wrong page

### ISSUE THREAD

**Issue by mubarak-j** [aws-samples/aws-cudos-framework-deployment#387]
In README.md file, under `Dashboard documentation`, the following URLs don't point directly to their respective dashboards

[CUDOS Dashboard](https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/2b_cudos_dashboard/)
[Cost Intelligence Dashboard](https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/2a_cost_intelligence_dashboard/)
[KPI Dashboard](https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/2c_kpi_dashboard/)

Instead, they redirect to https://www.wellarchitectedlabs.com/index.html

**Comment by iakov-aws** [comment]
This was fixed. Thanks
