### ISSUE TITLE
trends.sh map failed due to the hardcoded table name in trends.sh

### ISSUE THREAD

**Issue by yinlei100** [aws-samples/aws-cudos-framework-deployment#39]
The table name in  trends.sh > map was hardcoded to "cost_usage" which causes the script run to fail.  It should be replaced by the parameter "${athena_cur_table_name}".

**Comment by yinlei100** [comment]
PR: https://github.com/yinlei100/aws-cudos-framework-deployment/pull/1

**Comment by darken99** [comment]
Please create a pull request, we'll review and merge

**Comment by yinlei100** [comment]
PR: #41 https://github.com/aws-samples/aws-cudos-framework-deployment/pull/41

**Comment by darken99** [comment]
fixed by #41
