### ISSUE TITLE
Update dashboards created from analysis

### ISSUE THREAD

**Issue by hansarh** [aws-samples/aws-cudos-framework-deployment#395]
I'm wondering what the best workflow is for updating dashboards I have customized with custom fields and controls?

These custom dashboards are created based on saving the one of the standard dashboard, example cudos, to an analysis and adding custom configuraiton which then is published to a new dashboard. So when updating the standard dashboard those changes are not reflected to the customized dashboards I've created.

**Comment by iakov-aws** [comment]
Unfortunately today it is not possible. Once you create an analysis it is independent object. The update procedure will only impact dashboard provided with the framework, not analysis and dashboards that are 'forked' from it. 

Probably with a feature 'dashboard as code' it will be theoretically possible but we do not have an ETA of this feature from Quicksight.
