### ISSUE TITLE
Some permissions are missing in minimal permission

### ISSUE THREAD

**Issue by yinlei100** [aws-samples/aws-cudos-framework-deployment#40]
prepare and cleanup are failing because the following two permissions are missing in the minimal permissions:

glue:BatchDeleteTable
glue:CreateTable

In addition, if the customer would like to set up the entire framework using a non-admin user, additional permissions would be required for implementing the prerequisites, e.g. CloudFormation permission.

**Comment by darken99** [comment]
[minimal_permissions.json](https://github.com/aws-samples/aws-cudos-framework-deployment/blob/5b9b65061474a4e13ee8ad784debbdbfdf43948b/assets/minimal_permissions.json) contains permissions required by all dashboards
