### ISSUE TITLE
Error deploying cloudformation template

### ISSUE THREAD

**Issue by mbuotidem** [aws-samples/aws-cudos-framework-deployment#402]
I'm following the guide at : https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/deploy_dashboards/ and I'm unable to deploy the Dashboard using the provided [template](https://console.aws.amazon.com/cloudformation/home#/stacks/new?&templateURL=https://aws-managed-cost-intelligence-dashboards.s3.amazonaws.com/cfn/cid-cfn.yml&stackName=Cloud-Intelligence-Dashboards ). 

The stack fails when it tries to create `CidResourceLambdaLayer`. 

```
Error occurred while GetObject. S3 Error Code: NoSuchBucket. 
S3 Error Message: The specified bucket does not exist (Service: AWSLambdaInternal; Status Code: 400; 
Error Code: InvalidParameterValueException; Request ID: ad3b78c7-7216-431f-89dd-30e769b3b58f; Proxy: null)
```

Any thoughts?

**Comment by iakov-aws** [comment]
Cur bucket must exist. Please deploy a CUR and provide a CUR bucket to the template parameters

Also if you choose TAO or COD dashboards you must have Data Collection Lab Installed https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/ and provide a respective bucket.

**Comment by iakov-aws** [comment]
Please reopen if needed

**Comment by mbuotidem** [comment]
> Cur bucket must exist. Please deploy a CUR and provide a CUR bucket to the template parameters
> 
> Also if you choose TAO or COD dashboards you must have Data Collection Lab Installed https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/ and provide a respective bucket.

Unfortunately, I am unable to implement your suggestion because the bucket for the Data Collection Lab does not exist in my region. I have opened https://github.com/awslabs/aws-well-architected-labs/issues/751 to track that.

**Comment by mbuotidem** [comment]
@iakov-aws when you say reopen, do you mean create a new issue? I don't think I'm allowed to reopen an issue I didn't close myself.
