### ISSUE TITLE
Dataset (compute_optimizer_all_options) failed refresh  due to hardcoded s3 bucket name

### ISSUE THREAD

**Issue by mubarak-j** [aws-samples/aws-cudos-framework-deployment#408]
I opted for a custom bucket name when deploying Compute Optimizer Dashboard instead of the default option `s3://costoptimizationdata{account_id}` when I attempted to refresh one of the datasets `compute_optimizer_all_options` failed with the error bucket doesn't exist. This is the only dataset that seems to reference the hardcode default value, the others detect the custom s3 bucket.

```yaml
Refresh error details
Ingestion Id

183ef42a-0185-48d8-a88b-f59ddd00ea53

Error type:

SQL_EXCEPTION [Learn more](https://docs.aws.amazon.com/console/quicksight/errors)
This is a general SQL error. This can be caused by query timeouts, resource constraints, unexpected DDL alterations before or during a query, and other database errors. Check your database settings and your query, and try again.

Error details:

com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1GWC01DFWXN0XNSF; S3 Extended Request ID: qjl8Enj5MpHedsyXBvNf6unQxP2qE4WtFfU5uoGpJVKc2ILZpb3i7CxgqKZUnhAiIFOV1yLBxj2m3PSgUK1PvA==; Proxy: null), S3 Extended Request ID: qjl8Enj5MpHedsyXBvNf6unQxP2qE4WtFfU5uoGpJVKc2ILZpb3i7CxgqKZUnhAiIFOV1yLBxj2m3PSgUK1PvA== (Path: s3://costoptimizationdata[redacted-account-id]/Compute_Optimizer/Compute_Optimizer_ec2_instance) [Execution ID: 6419c812-4e22-48f0-a96f-3ebf148bb58d]
```

**Comment by iakov-aws** [comment]
Hi, 
Do you have Data Collection Lab installed https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/  and pointing to the bucket you specified? 


Did you installed via cfn or cli ?

**Comment by iakov-aws** [comment]
Can you also check in Athena the location field?
```
SHOW CREATE TABLE `compute_optimizer_ec2_instance_lines`;
```

**Comment by mubarak-j** [comment]
Yes, I did complete [optimization_data_collection](https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/ ) and the bucket I specified as a parameter in [this step](https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/2_deploy_main_resources/) has been created. I deployed all stacks using cfn templates listed in the guide. 

The location field in Athena output points to the default value `costoptimizationdata{account_id}`, not the one I specified in my cfn parameter:
```java
LOCATION
  's3://costoptimizationdata[redacted_account_id]/Compute_Optimizer/Compute_Optimizer_ec2_instance'
```
Is there a single place for me to fix this value? or is this something that is referenced in many places and will require a cleaner fix?

**Comment by mubarak-j** [comment]
Looking at Glue tables, the table `ta_organizational_view_reports` has the correct location. But the following 4 tables have the wrong/default bucket name:
```yaml
compute_optimizer_ebs_volume_lines
compute_optimizer_ec2_instance_lines
compute_optimizer_auto_scale_lines
compute_optimizer_lambda_lines
```

So I'm guessing at least the trusted advisor data should be in the bucketright? but the bucket is still empty after more than 24 hrs since I deployed compute optimizer & TA dashboards.

**Comment by iakov-aws** [comment]
1. about Comute Optimizer : Probably the default bucket name was used on deploy. Today CFN update is not updating SQL views and tables. So they stay as they were deployed the first time. 

If you are using CFN deployment of CID i would suggest you delete COD dashboards by updating the stack with 'Compute Optimizer Dashboard = No' and then re-create it updating with 'Compute Optimizer Dashboard = Yes'

Alternatively you can use cil tool in CloudShell or any other environment that has access to your aws account

``` 
cid-cmd update --recursive --force
```
and enter the right path when prompted.

2. About TAO please check if you have Business, Enterprise On-Ramp, or Enterprise Support level. This is a prerequisite  to use Support API.  
Also check if you triggered Account Collector function after the deployment as described in the 3rd step of data collection lab https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/3_test_modules/

By default data colelction happens every 14 days

If all triggered but data are not there, Please check the cloudwatch log of a function that process Trusted Advisor (search Trusted_Advisor in your lambda functions ). If there is an access error you need to check if you installed a stackset with role permissions or the role name or prefix parameters are different between CFNs.

**Comment by mubarak-j** [comment]
Thank you, that helped solve the issues for me! Running `cid-cmd update` did the trick and changed frequency to `rate(1 day)` and I can see data in the TA dashboard now.

if you don't mind, one last question/observation, in `compute-optimizer-dashboard` i see compute-optimizer suggestions showing for EBS/EC2/AutoScale. But the lambda tab shows `No Data, There was no data found for this visual` although in each individual account in AWS Org I see recommendations for shown for lambda functions. What could be the cause here?
