### ISSUE TITLE
[CloudFormation] Accept more manual CUR s3 bucket names

### ISSUE THREAD

**Issue by k24dizzle** [aws-samples/aws-cudos-framework-deployment#453]
I tried to set up the dashboards via the CloudFormation method. We have manually set up our CUR reports, and they have been running for a while and are connected to an s3 bucket. 

However, the CloudFormation failed because our CUR reports are located in a s3 bucket with the following name:`s3://company-cost-usage-aws-mbr/mbr/company-aws-mbr/` that the CloudFormation template doesn’t seem to be able to process.  So I was running into the error [here](https://github.com/aws-samples/aws-cudos-framework-deployment/blob/b6ed2e20fbcd9b5384eb662a2e5c719896a1e5f0/cfn-templates/cid-cfn.yml#L653).

Would it be possible to modify the template to accept this custom bucket name?

Right now it seems only:
`s3://(bucket)/cur` or `s3://(bucket)/(curprefix)/(curname)/(curname)` is accepted.

**Comment by iakov-aws** [comment]
yes, 
in your case it is most likely: 
 s3://company-cost-usage-aws-mbr/mbr/company-aws-mbr/company-aws-mbr/

please check if you have this folder
if not you will need to create a CUR with athena integration

**Comment by k24dizzle** [comment]
Sounds good, I could copy over the s3 bucket from `s3://company-cost-usage-aws-mbr/mbr/company-aws-mbr/company-aws-mbr/` to `s3://company-cost-usage-aws-mbr/mbr/company-aws-mbr/`, and modify the CUR report to go into that bucket?

But the bucket themselves would be exactly the same, from CloudFormation's perspective could it just look into the original bucket?

**Comment by iakov-aws** [comment]
Please do not copy anything. 
Cur must be created this way: 
 `s3://company-cost-usage-aws-mbr/mbr/company-aws-mbr/company-aws-mbr/`

if it is created with Athena integration (and it is a strong requirement) then the stucture of cur folders is: 

`s3://(bucket)/(curprefix)/(curname)/(curname)`

no coping needed

**Comment by iakov-aws** [comment]
Pease let me know if still an issue
