### ISSUE TITLE
AWS QuickSight SPICE limit exceeded

### ISSUE THREAD

**Issue by k24dizzle** [aws-samples/aws-cudos-framework-deployment#454]
```
CRITICAL - AWS QuickSight SPICE limit exceeded. Add SPICE here https://quicksight.aws.amazon.com/sn/admin#capacity .
```

Any advice on solving the following issue?

I tried to add more SPICE in the quicksight settings, up to 500GB, and rerunning the command line tool, but each time I ran into this error.
- Is our CUR data too big to ingest into QuickSight? This seems unlikely because our CUR s3 bucket is only ~30 GIB.
- Or does it take some time for a SPICE purchase request to go through?

Either way, would it be possible for the tool to output the amount of SPICE needed to be purchased so that the dataset can be created?

**Comment by iakov-aws** [comment]
Please make sure you are adding SPICE in teh right region.

**Comment by k24dizzle** [comment]
Thank you! that seemed to work
