### ISSUE TITLE
Missing view when updating from Trusted Advisor dashboard 13 -> 14

### ISSUE THREAD

**Issue by hansarh** [aws-samples/aws-cudos-framework-deployment#462]
I'm unsure what I should enter when trying to update trusted advisor dashboard from v13 -> 14 I get prompted 
```
Updating dataset: "ta-organizational-view"
Detected views: 
Missing views: ta_org_view

[view-ta-organizational-view-reports-s3FolderPath] Required parameter: s3FolderPath (Trusted Advisor Organization View report S3 path):
```

I have the dataset ta-organizational-view as an athena tables but not the "ta_rog_view" view. When I'm prompted to enter the s3FolderPath I get confused since this seems to refer to the "Trusted Advisor Organizational View" [data collection method](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/trusted-advisor-dashboards/dashboards/1_prerequistes/#enable-trusted-advisor-data-collection) for collecting optimization data which we don't. We use the recommended rusted Advisor API with [Optimization Data Collection lab](https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/) 

Should I enter the s3FolderPath which in our case would be a path within our optimization data bucket, used to generate ta-organizational-view dataset?
Or can we implement the ta_org_view somehow before running this update command?

the full command output: 
```
[cloudshell-user@ip-10-6-32-106 ~]$ cid-cmd -vvv update
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.2.10 Beta

Loading plugins...
        Core loaded


Logging level set to: DEBUG
Checking AWS environment...
        profile name: default
        accountId: 514114933583
        AWS userId: AWSReservedSSO_
        Region: eu-west-1


Discovering deployed dashboards...  [####################################]  100%  "Trusted Advisor Organizational View" (ta-organiza          

? [dashboard-id] Please select installation(s) from the list: Trusted Advisor Organizational View (arn:aws:quicksight:eu-west-1:514114933583:dashboard/ta-organizational-view, healthy, update available 13->14)

Latest template: arn:aws:quicksight:us-east-1:223485597511:template/ta-organizational-view/version/14
An update is available:
                   Deployed -> Latest
  CID Version      v1.4.0      v2.0.0
  TemplateVersion  13          14    

? [confirm-recursive] This is a major update and require recursive action. This could lead to the loss of dataset customization. Continue anyway?: yes

Required datasets: 
 - ta-organizational-view

Updating dataset: "ta-organizational-view"
Detected views: 
Missing views: ta_org_view

? [view-ta-organizational-view-reports-s3FolderPath] Required parameter: s3FolderPath (Trusted Advisor Organization View report S3 path): s3://costoptimizationdata514114933583/trusted-advisor/trusted-advisor-data
```

**Comment by yprikhodko** [comment]
In recent version of  [Optimization Data Collection lab](https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/) we changed the default path s3://costoptimizationdata{account}/trusted-advisor/trusted-advisor-data while if you have older version deployed you might have path like s3://costoptimizationdata{account}/optics-data-collector/ta-data/.
When cid-cmd asks for the path you should put the one where you have TA data collected (disregard suggested default path in your case). In the latest version of TAO we added Athena view ta_org_view and made schema changes to the QuickSight datasets hence update process requires to provide the s3 path again.
