### ISSUE TITLE
An error occurred (AccessDeniedException) when calling the DescribeTemplate operation: User

### ISSUE THREAD

**Issue by 10shweta** [aws-samples/aws-cudos-framework-deployment#498]
Hi Team,
Trying to run cloud formation template to deploy Quicksight Dashboards (Following this link https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/deploy_dashboards/)
After implementing Step 1& 2 (set up for Cur Report) 
Stuck on step 4 following this link
 (https://console.aws.amazon.com/cloudformation/home#/stacks/create/review?templateURL=https://aws-managed-cost-intelligence-dashboards.s3.amazonaws.com/cfn/cid-cfn.yml&stackName=Cloud-Intelligence-Dashboards&param_DeployCUDOSDashboard=yes&param_DeployKPIDashboard=yes&param_DeployCostIntelligenceDashboard=yes)

Using AWS user with Administartor Access to deploy the cloud formation template on the data collection account still facing issue on describe template. Attached is the screenshot of the same.
![image](https://user-images.githubusercontent.com/127412973/224040712-4ca3cf28-1a93-4eb1-a4d9-d569d919a4a3.png)

**Comment by iakov-aws** [comment]
Most probably you will need to allow describe Amazon QuickSight templates in us-east-1

**Comment by 10shweta** [comment]
After adding region to the scp it worked,
Thanks!
