### ISSUE TITLE
Data is not visible for last 6 months in KPI-Dashboard

### ISSUE THREAD

**Issue by nirooptgd** [aws-samples/aws-cudos-framework-deployment#505]
Hi Team,
I could able to see only last4 months data even though , if I selected for last 6 Months in Billing-period filter. If I selected less than 4 months I can able to see the data for selected months Pleas see the attached snapshot for reference. It would be great if I get any hep from anyone.

![image](https://user-images.githubusercontent.com/94053316/226301718-a7aa3f02-13c2-4ed4-8172-80e1f8e33ba2.png)

![image](https://user-images.githubusercontent.com/94053316/226301768-ad0cc733-3c60-44e9-8c12-77a12e4b7eac.png)

Thanks,
Niroop

**Comment by iakov-aws** [comment]
There is a limit on the number of months in the query. You can change that to get more months. 

https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/cid/builtin/core/data/queries/kpi/kpi_instance_all_view.sql#L72

**Comment by nirooptgd** [comment]
Hi @iakov-aws , Thanks for the reply.
I have already set the 6 Month in the given query. Please let mw know if any other parameter to check.
![image](https://user-images.githubusercontent.com/94053316/226326765-0cbcdab3-3853-48a4-a6c3-4abd25907ed6.png)
