### ISSUE TITLE
KPI-Dashboard: Standard IA to Glacier Instant Retrieval Savings Opportunities

### ISSUE THREAD

**Issue by nirooptgd** [aws-samples/aws-cudos-framework-deployment#506]
Hi Team,
Can anyone help to resolve the below error .

![image](https://user-images.githubusercontent.com/94053316/227131931-d5c2d9ee-a638-474e-9a90-0688adda19d5.png)

**Comment by yprikhodko** [comment]
Could you please click show details and provide them here?

**Comment by iakov-aws** [comment]
cleanup - Closing the issue. Please contact your TAM to organize a debug session if still an issue
