### ISSUE TITLE
CUR table is not updated

### ISSUE THREAD

**Issue by mliner** [aws-samples/aws-cudos-framework-deployment#507]
Hi,
I am using the CID solution for a while. I have multiple AWS organizations connected to one centralised account with all the machinery deployed. However last week I noticed that new data are not being shown in CUDOS dashboard. After some investigation I've found out that CUR athena table is not updated anymore by the crawler. Instead new tables per s3 path (bucket/cur/accountid/cid/) are being added and therefore summary view does not show newly added data. I haven't did any changes to crawler configuration. Any clues where is the problem?

I think that crawler should combine all parquet stuff into one table if the schemas are the same right?

![Screenshot 2023-03-27 at 16 51 38](https://user-images.githubusercontent.com/7250180/227977728-0673d04b-dd58-42f5-b79f-1bad046f7cba.png)

**Comment by iakov-aws** [comment]
Yes, if other tables are created this normally linked to Crawler Configuration.

Can you provide crawler configuration?
```
 aws glue get-crawler --name  CidCrawler
```
Must be something like this: https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/cfn-templates/cid-cfn.yml#L742

**Comment by mliner** [comment]
` {
    "Crawler": {
        "Name": "CidCrawler",
        "Role": "cloud-intelligence-dashboards-CidCURCrawlerRole-XXXXXXXXXXXXX",
        "Targets": {
            "S3Targets": [
                {
                    "Path": "s3://cid-XXXXXXXXXXXXXX-shared/cur/",
                    "Exclusions": [
                        "**.json",
                        "**.yml",
                        "**.sql",
                        "**.csv",
                        "**.csv.metadata",
                        "**.gz",
                        "**.zip",
                        "**/cost_and_usage_data_status/*",
                        "aws-programmatic-access-test-object"
                    ]
                }
            ],
            "JdbcTargets": [],
            "MongoDBTargets": [],
            "DynamoDBTargets": [],
            "CatalogTargets": [],
            "DeltaTargets": []
        },
        "DatabaseName": "cid_cur",
        "Description": "A recurring crawler that keeps your CUR table in Athena up-to-date.",
        "Classifiers": [],
        "RecrawlPolicy": {
            "RecrawlBehavior": "CRAWL_EVERYTHING"
        },
        "SchemaChangePolicy": {
            "UpdateBehavior": "UPDATE_IN_DATABASE",
            "DeleteBehavior": "LOG"
        },
        "LineageConfiguration": {
            "CrawlerLineageSettings": "DISABLE"
        },
        "State": "READY",
        "Schedule": {
            "ScheduleExpression": "cron(0 2 * * ? *)",
            "State": "SCHEDULED"
        },
        "CrawlElapsedTime": 0,
        "CreationTime": "2023-03-03T00:35:50+01:00",
        "LastUpdated": "2023-03-03T00:35:50+01:00",
        "LastCrawl": {
            "Status": "SUCCEEDED",
            "LogGroup": "/aws-glue/crawlers",
            "LogStream": "CidCrawler",
            "MessagePrefix": "8660ae0e-2d98-4981-a2b7-2dc33d94b9c1",
            "StartTime": "2023-03-27T09:57:55+02:00"
        },
        "Version": 2,
        "Configuration": "{\"Version\":1.0,\"CrawlerOutput\":{\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}},\"Grouping\":{\"TableGroupingPolicy\":\"CombineCompatibleSchemas\"}}",
        "LakeFormationConfiguration": {
            "UseLakeFormationCredentials": false,
            "AccountId": ""
        }
    }
}`

**Comment by iakov-aws** [comment]
Please comment / reopen if still an issue
