### ISSUE TITLE
Guidance crawler

### ISSUE THREAD

**Issue by ashraf133** [aws-samples/aws-cudos-framework-deployment#509]
Hello,

I have already an s3 bucket which contains CUR in management account.
I have installed the cid-cfn.yml in a data collection account ( different thant root) everything seems to be ok but the crawler in data account can't get data from the s3 which is in root account/
Here is the modified policies for crawler and s3 and the log : 

s3 policy contains: 

`` {
            "Sid": "CID",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:GetObject",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*",
                "arn:aws:s3:::mybucket"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalOrgID": "o-xxxxxx"
                }
            }
        }
``

crawler role contains: 
``
{
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*",
                "arn:aws:s3:::mybucket"
            ],
            "Effect": "Allow"
        }
``
crawler logs: 
``
ERROR : Not all read errors will be logged. com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: EWGRJND7S5XZ17GG; S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=; Proxy: null), S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=
ERROR : Not all read errors will be logged. com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: EWGRJND7S5XZ17GG; S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=; Proxy: null), S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=
ERROR : Not all read errors will be logged. com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: EWGRJND7S5XZ17GG; S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=; Proxy: null), S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=
ERROR : Not all read errors will be logged. com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: EWGRJND7S5XZ17GG; S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=; Proxy: null), S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=
ERROR : Not all read errors will be logged. com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: EWGRJND7S5XZ17GG; S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=; Proxy: null), S3 Extended Request ID: kYnTruEJwe0dCgNvYdUBUoeWzKR9notex3cwLVdCrIBkOOdpb3F775q2mCKOL6zEJpI11L1G1Ps=

BENCHMARK : Classification complete, writing results to database cid_cur

INFO : Crawler configured with Configuration {"Version":1.0,"CrawlerOutput":{"Tables":{"AddOrUpdateBehavior":"MergeNewColumns"}},"Grouping":{"TableGroupingPolicy":"CombineCompatibleSchemas"}} and SchemaChangePolicy {"UpdateBehavior":"LOG","DeleteBehavior":"LOG"}. Note that values in the Configuration override values in the SchemaChangePolicy for S3 Targets.

INFO : Found table cid with no matching schema at the table's S3 location

BENCHMARK : Finished writing to Catalog

BENCHMARK : Crawler has finished running and is in state READY
``

the crawler is unable to collect data from s3 in another account

**Comment by iakov-aws** [comment]
Please check the advanced setup. This includes cur replication on s3 level. https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/deploy_dashboards/#advanced-setup


We do not recommend cross account access to s3. It is possible but very error prone and hard to debug. S3 replication is cheap and replicated fies are deleted with lifecycle policy so almost no additional charges. 

Also if you use cfn to deploy the new cur tou can allways request a backfill 3 years of historical data, so no need to keep legacy cur unless you need more data than 3 years.
