### ISSUE TITLE
API: s3:SetBucketEncryption Access Denied

### ISSUE THREAD

**Issue by 10shweta** [aws-samples/aws-cudos-framework-deployment#515]
Hi Team, 

We are running cloud formation template in Data Collection account and getting below error
Step 1 : https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/deploy_dashboards/)

Please note we are having Admin Permission on this account.

![image](https://user-images.githubusercontent.com/127412973/230831337-b767490d-901f-4010-81d3-b777345b18ff.png)

Thanks
Shweta

**Comment by iakov-aws** [comment]
Hello, this might be an issue with SCP. Another likely cause is that the role does not have `iam:PassRole` permission.

Here is an experimental CFN that adds needed permissions to an existing role. This is a WIP but you can check some permissions needed there:  

https://github.com/aws-samples/aws-cudos-framework-deployment/pull/504/files#diff-0342f24fbbce4d883718318ebbdb459ec4ec0926e75e7e96129adb84280593ecR249

**Comment by 10shweta** [comment]
> Hello, this might be an issue with SCP. Another likely cause is that the role does not have `iam:PassRole` permission.
> 
> Here is an experimental CFN that adds needed permissions to an existing role. This is a WIP but you can check some permissions needed there:
> 
> https://github.com/aws-samples/aws-cudos-framework-deployment/pull/504/files#diff-0342f24fbbce4d883718318ebbdb459ec4ec0926e75e7e96129adb84280593ecR249

Thanks for taking out time and suggesting this permission list extremely helpful. 
We tried making changes in SCP where we have exempted ARN which helped us to move ahead.  

  "ArnNotLike": {
          "aws:PrincipalARN": [
            "arn:aws:iam::*:role/AWSCloudFormationStackSetExecutionRole",
            "arn:aws:iam::xxxxxxxxx-admin-caa-role"
          ]
        }

**Comment by iakov-aws** [comment]
Thanks for the update!
