### ISSUE TITLE
Embedded stack arn:aws:cloudformation

### ISSUE THREAD

**Issue by 10shweta** [aws-samples/aws-cudos-framework-deployment#516]
Hi Team, 

We are deploying Compute optimiser dashboard, While running Cloud formation template on  Data Collection account getting below error : 

Embedded stack arn:aws:cloudformation:ap-south-1:xxxxxx:stack/OptimizationDataCollectionStack1-ComputeOptimizerModule-xxxxxx was not successfully created: The following resource(s) failed to create: [ReplicaitonBucketsStackSet].

_Creating using the following stack
https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/2_deploy_main_resources/_

Stack and Stackset created on Management ran successfully, without any issue.

Can you please suggest what can be the probable issue

Thanks
Shweta

**Comment by iakov-aws** [comment]
can you check in the deleted stacks in cloud formation the stack that starts with "StackSet-"  and check the failure reason? 

Most probably, you need to add another exception in your SCP 

There are 2 roles involved: 

1. https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/module-compute-optimizer.yaml#L132
2. https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/module-compute-optimizer.yaml#L86

**Comment by iakov-aws** [comment]
Hello Shweta, were you able to allow these roles and deploy the stack?

**Comment by iakov-aws** [comment]
Please comment / reopen if still an issue
