### ISSUE TITLE
How to access the most recent data in the KPI Goals Tracking Widget (KPI-Dashboard)

### ISSUE THREAD

**Issue by nirooptgd** [aws-samples/aws-cudos-framework-deployment#520]
In the KPI-dashboard, I would want to see the data for the last 7 days for KPI Goals Tracking. I've tried, but I don't see any data for the message's selected period. I need the data for the last x days; can anyone help?
![image](https://user-images.githubusercontent.com/94053316/232537377-6ea0cb69-0c5c-4d7f-80d7-018e055aa827.png)

**Comment by iakov-aws** [comment]
Sorry for the late answer. if still an isssue please check the status of datasets kpi* if they are updated correctly. Please reopen or contact your TAM if still an issue
