### ISSUE TITLE
Running the cid-cmd to deploy any Dashboard fails with "ValueError: A list of choices needs to be provided." error

### ISSUE THREAD

**Issue by scampuza** [aws-samples/aws-cudos-framework-deployment#532]
Hi there AWS team !

I was trying to use the `cid-cmd` tool to deploy the Trends Dashboard.  For some reason, I am getting this error on the last step, after selecting the Athena workgroup to use:

? [athena-workgroup] Select AWS Athena workgroup to use: primary-athena-v3

Traceback (most recent call last):
  File "/usr/local/bin/cid-cmd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cid/cli.py", line 28, in wrapper
    res = func(ctx, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cid/cli.py", line 107, in deploy
    ctx.obj.deploy(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/cid/common.py", line 164, in wrap
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cid/common.py", line 266, in deploy
    self._deploy(dashboard_id, recursive, update, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/cid/common.py", line 332, in _deploy
    self.create_datasets(required_datasets, dashboard_datasets, recursive=recursive, update=update)
  File "/usr/local/lib/python3.11/site-packages/cid/common.py", line 975, in create_datasets
    if self.create_or_update_dataset(dataset_definition, dataset_id, recursive=recursive, update=update):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cid/common.py", line 1110, in create_or_update_dataset
    datasource_id = get_parameter(
                    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cid/utils.py", line 216, in get_parameter
    result = questionary.select(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/questionary/prompts/select.py", line 121, in select
    raise ValueError("A list of choices needs to be provided.")
ValueError: A list of choices needs to be provided.

I really appreciate any help !

**Comment by iakov-aws** [comment]
The error is missleading and it will be fixed in the next release.  

Looks like you do not have an athena datasource available in QS.

**Comment by scampuza** [comment]
Hi @iakov-aws ! 

Thanks for your reply.  

We do have some Datasets/Datasources in QuickSight:

<img width="637" alt="image" src="https://github.com/aws-samples/aws-cudos-framework-deployment/assets/8714407/9e3b888d-2e83-40a1-9ef1-70526edd9d9c">

We have the CUDOS dashboard up and running.  Do we need additional data sources?

**Comment by iakov-aws** [comment]
Interesting. Can you check if your role can list dataSources? 
```bash
export account_id=$(aws sts get-caller-identity --query Account --output text)
aws quicksight list-data-sources --aws-account-id $account_id --query 'DataSources[?Type==`ATHENA`].{Status: Status, Arn: Arn}'
```

**Comment by scampuza** [comment]
Yes I can !

[
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/10b40929-d2e1-434f-a5d8-3bc77be27489"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/1bd07e57-6f1b-4a66-9e4d-aabe6f6ab69b"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/27fe3567-ce26-4773-8071-fbd660db51bd"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/4a62e422-fbe0-41fc-a88e-a83946736f1c"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/59c587fe-95ca-434c-9851-42703bd1195c"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/703b2ae3-89e7-4563-b397-e9c4a946cfc8"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/73c2a5fa-568d-4048-9ca3-c4956107ca4d"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/7cef6878-c31e-4885-939b-2512b3bf0cc2"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/901a1003-0b90-445a-8dd7-36f4418aa423"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/aa169c25-582b-4b90-860f-409882827547"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/ab1fe188-18b1-45ff-bf2f-ce122b236d85"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/QSCURDataSource"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/b2047954-ad69-4470-bf60-c2050f146e48"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/c684b766-91df-4883-b274-129a24e18883"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/db3bfebb-7442-4cae-b693-7e9c8b1a6328"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/e984e1fd-a5a2-4153-9512-9481a60b0f75"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/fe9179ae-166a-4d9d-93a9-c4cc580f9608"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/ff50f2cb-d113-4e0f-bf0c-580b0012f3ae"
    }
]
(END

**Comment by iakov-aws** [comment]
Sorry, looks like need another filter on workgroup:


aws quicksight list-data-sources --aws-account-id $account_id --query 'DataSources[?(Type==`ATHENA` && DataSourceParameters.AthenaParameters.WorkGroup==`primary-athena-v3`)].{Status: Status, Arn: Arn}'

**Comment by scampuza** [comment]
Hi @iakov-aws .  

I just realized that I should be using a different Athena WorkGroup.  This the output:

[
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/10b40929-d2e1-434f-a5d8-3bc77be27489"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/1bd07e57-6f1b-4a66-9e4d-aabe6f6ab69b"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/27fe3567-ce26-4773-8071-fbd660db51bd"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/4a62e422-fbe0-41fc-a88e-a83946736f1c"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/59c587fe-95ca-434c-9851-42703bd1195c"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/703b2ae3-89e7-4563-b397-e9c4a946cfc8"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/73c2a5fa-568d-4048-9ca3-c4956107ca4d"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/7cef6878-c31e-4885-939b-2512b3bf0cc2"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/901a1003-0b90-445a-8dd7-36f4418aa423"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/aa169c25-582b-4b90-860f-409882827547"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/ab1fe188-18b1-45ff-bf2f-ce122b236d85"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/QSCURDataSource"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/b2047954-ad69-4470-bf60-c2050f146e48"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/c684b766-91df-4883-b274-129a24e18883"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/db3bfebb-7442-4cae-b693-7e9c8b1a6328"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/e984e1fd-a5a2-4153-9512-9481a60b0f75"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/fe9179ae-166a-4d9d-93a9-c4cc580f9608"
    },
    {
        "Status": "CREATION_SUCCESSFUL",
        "Arn": "arn:aws:quicksight:us-east-1:135813213455:datasource/ff50f2cb-d113-4e0f-bf0c-580b0012f3ae"
    }
]

**Comment by iakov-aws** [comment]
Ok. If you use this different Athena workgroup is it better with cid-cmd tool?

**Comment by iakov-aws** [comment]
Please reopen or comment if still an issue
