### ISSUE TITLE
Invalid length for parameter QueryExecutionContext.Database, value: 0, valid min length: 1

### ISSUE THREAD

**Issue by albano93** [aws-samples/aws-cudos-framework-deployment#54]
Hi,
I have been introduced to Cudos by a AWS TAM. This is a great app that we would like to deploy. Running manually was not an issue but using the automated deployment I am facing an issue when running the command  "./shell-script/customer-cudos.sh config":
[cloudshell-user@ip-10-0-68-168 cudos]$ ./shell-script/customer-cudos.sh config
Checking environment
AWS CLI version...2.2.20...ok
Fetching AWS Account ID...ok
Enter QuickSight region: us-east-1
Enter QuickSight Identity region [default : us-east-1]: 
Fetching Athena Database names...
Discovered Athena Database names.
Please select which one to use:
----
1) athenacurcfn_c_u_r
2) sampledb
#? athenacurcfn_c_u_r
You have chosen 
Fetching Athena Table names...

Parameter validation failed:
Invalid length for parameter QueryExecutionContext.Database, value: 0, valid min length: 1

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --query-execution-id: expected one argument

Discovered Athena Table names. . Please select which one to use:
----

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --query-execution-id: expected one argument

[cloudshell-user@ip-10-0-68-168 cudos]$ ./shell-script/customer-cudos.sh config
Checking environment
AWS CLI version...2.2.20...ok
Fetching AWS Account ID...ok
Enter QuickSight region: us-east-1
Enter QuickSight Identity region [default : us-east-1]: 
Fetching Athena Database names...
Discovered Athena Database names.
Please select which one to use:
----
1) athenacurcfn_c_u_r
2) sampledb
#? athenacurcfn_c_u_r
You have chosen 
Fetching Athena Table names...

Parameter validation failed:
Invalid length for parameter QueryExecutionContext.Database, value: 0, valid min length: 1

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --query-execution-id: expected one argument

Discovered Athena Table names. . Please select which one to use:
----

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --query-execution-id: expected one argument

[cloudshell-user@ip-10-0-68-168 cudos]$ 

Can you please help ?

**Comment by petrokashlikov** [comment]
@albano93 can you please provide screenshot of output when you get this error?

**Comment by kody-actzero** [comment]
I am getting the same issue. See attached screenshot.
![Screen Shot 2021-07-28 at 9 02 23 AM](https://user-images.githubusercontent.com/56694014/127357138-7a35e23a-0b02-4858-9523-34e16299c34a.png)

**Comment by darken99** [comment]
@kody-actzero you have to configure Athena's workgroup output location as described in https://cudos.workshop.aws/prerequisites_multipayer/prepare-athena.html, step 5

**Comment by megareez** [comment]
In addition to that you need to set up output location on the WORKGROUP level, not just in UI.
