### ISSUE TITLE
Athena Error

### ISSUE THREAD

**Issue by chandankashyap19** [aws-samples/aws-cudos-framework-deployment#547]
Hello Team, 

I am getting the below error while deploying the Cudos dashboard through Cloudshell.

`CRITICAL - Athena query failed: Invalid column type for column ri_sp_arn: Varchar length 0 out of allowed range [1, 65535]`

Please help me in fixing it. This is fresh installation.

`CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.2.14 Beta`

**Comment by bmurphey** [comment]
I ran into this same error.  In my case, we're not using Savings Plans/Reserved Instances at the moment, so I tried the approach [here](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/code/1_view1/#view-1---summary-view).  This allowed the dashboard deployment to succeed.  I'm not sure if this is the best approach, and I haven't had to do this with previous deployments, so I wonder if something has changed?

**Comment by yprikhodko** [comment]
Could you please run `cid-cmd deploy -vv` and provide us cid.log created. Please make sure you remove/mask any account ids or other sensitive info before sharing the log

**Comment by iakov-aws** [comment]
A potential fix was merged to main branc 
please can you test?

`pip3 install git+https://github.com/aws-samples/aws-cudos-framework-deployment@main`
`cid-cmd deploy`

**Comment by chandankashyap19** [comment]
I followed the steps mentioned by @bmurphey but didn't help me succeed in the deployment. However manual creation of [summry_view](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/code/1_view1/#view-1---summary-view:~:text=but%20do%20not%20have%20Savings%20Plans-,The%20query%20is%20the%20same%20as%20the%20first%20query%2C%20except%20some%20of%20lines%20have%20been%20commented%20out.%20If%20your%20usage%20changes%20you%20can%20delete%20and%20recreate%20the%20required%20view%20with%20Savings%20Plans%20or%20Reserved%20Instance%20usage.,-Modify%20the%20following%20SQL%20query%20for) in Athena is helping in deploying the dashboard.

**Comment by iakov-aws** [comment]
Must be good with the latest version of CID. Please comment if still an issue
