### ISSUE TITLE
TAO -- (AccessDeniedException) when calling the DescribeTemplate operation

### ISSUE THREAD

**Issue by fitchtravis** [aws-samples/aws-cudos-framework-deployment#55]
Error:

Checking for updates...
Getting latest available source template version...
An error occurred (AccessDeniedException) when calling the DescribeTemplate operation: User: arn:aws:iam::xxxxxxxxxxxx:user/user.name is not authorized to perform: quicksight:DescribeTemplate on resource: arn:aws:quicksight:ap-southeast-2:223485597511:template/ta-organizational-view

Fix: add --region=us-east-1 to line 232 in the file shell-script/lib/common.sh

`231   latest_template_version=$(aws quicksight describe-template --query 'Template.Version.VersionNumber' \`
`232       --region=us-east-1 --aws-account-id ${sourceAccountId} --template-id ${sourceTemplateId})`

**Comment by darken99** [comment]
Feel free to submit a PR

**Comment by petrokashlikov** [comment]
> Feel free to submit a PR

@darken99  We should not explicitly set region in command.  
@fitchtravis If you run config step, it is setting region env variable and then you can proceed with update

**Comment by darken99** [comment]
> @darken99 We should not explicitly set region in command.
In this exact case we should as the template resides in us-east-1
