### ISSUE TITLE
Missing "line_item_amortized_cost" to display EC2 instances with actual cost

### ISSUE THREAD

**Issue by victorshinya** [aws-samples/aws-cudos-framework-deployment#555]
CUDOS Framework's missing any configuration to display EC2 instances cost with amortized / net amortized cost. As of briefly explained in [Understanding your AWS Cost Datasets: A Cheat Sheet](https://aws.amazon.com/blogs/aws-cloud-financial-management/understanding-your-aws-cost-datasets-a-cheat-sheet/) blog post, amortized / net amortized cost option is ideal and useful for customers who have purchased AWS Reservations such as Amazon EC2 Reserved Instance or Savings Plan.

User cannot find "line_item_amortized_cost" option on CUDOS to see the actual cost for the EC2 instance - considering the Savings Plan reduction in its monthly cost.

**Comment by yprikhodko** [comment]
Hi @victorshinya, 
Just to clarify:
Unblended costs represent your usage costs on the day they are charged to you - available in CUDOS
Amortized costs reflects the effective cost of the upfront and monthly reservation fees spread across the billing period - available in summary_view in CUDOS, however not available in customer_all dataset. You can add it to customer_all dataset by adding calculated field in QuickSight
`
ifelse(
    line_item_line_item_type = 'SavingsPlanCoveredUsage', savings_plan_savings_plan_effective_cost,
    line_item_line_item_type = 'SavingsPlanRecurringFee', savings_plan_total_commitment_to_date - savings_plan_used_commitment,
    line_item_line_item_type = 'SavingsPlanNegation', 0,
    line_item_line_item_type = 'SavingsPlanUpfrontFee', 0,
    line_item_line_item_type = 'DiscountedUsage', reservation_effective_cost,
    line_item_line_item_type = 'RIFee', reservation_unused_amortized_upfront_fee_for_billing_period + reservation_unused_recurring_fee, 
    line_item_line_item_type = 'Fee' and reservation_reservation_a_r_n <> 0, 0,
    line_item_unblended_cost
)`
In the future we plan to replace customer_all dataset with resource_view which will have amortized cost included.
