### ISSUE TITLE
Error updating TAO dashboard

### ISSUE THREAD

**Issue by fitchtravis** [aws-samples/aws-cudos-framework-deployment#56]
After running 

`./shell-script/tao.sh --action=update`

results in 
`Error: something went wrong, exiting`

enabling some bash debugging one can see the following

+ echo 'Checking for updates...'
Checking for updates...
+ echo -n 'Getting latest available source template version...'
Getting latest available source template version...++ aws quicksight describe-template --query Template.Version.VersionNumber --region=us-east-1 --aws-account-id 223485597511 --template-id ta-organizational-view
+ latest_template_version=11
+ '[' 0 -ne 0 ']'
+ echo 'latest available template version is 11'
latest available template version is 11
+ echo -n 'Getting currently deployed source version...'
Getting currently deployed source version...++ cut -f 6 -d :
++ aws quicksight describe-dashboard --dashboard-id ta-organizational-view --query Dashboard.Version.SourceEntityArn --aws-account-id xxxxxxxxxxxx
++ cut -f 4 -d /
+ current_dashboard_source_version=
+ '[' 0 -ne 0 ']'
+ echo 'latest available template version is '
latest available template version is 
+ '[' -eq 11 ']'
/home/cloudshell-user/aws-cudos-framework-deployment/tao/shell-script/lib/common.sh: line 249: [: -eq: unary operator expected
+ '[' -gt 11 ']'
/home/cloudshell-user/aws-cudos-framework-deployment/tao/shell-script/lib/common.sh: line 252: [: -gt: unary operator expected
+ echo 'Update available (  > 11 ), proceeding'
Update available (  > 11 ), proceeding
+ [[ auto != \a\u\t\o ]]
+ echo '
  ####### Pulling latest changes...

I think the problem lies around the fact that

`  current_dashboard_source_version=$(aws quicksight describe-dashboard --dashboard-id $dashboardId --query 'Dashboard.Version.SourceEntityArn' \
      --aws-account-id $account | cut -f 6 -d \: | cut -f 4 -d \/)`

Does not return an integer

**Comment by petrokashlikov** [comment]
@fitchtravis What does this command returns for you? 
```
 aws quicksight describe-dashboard --dashboard-id $dashboardId --query 'Dashboard.Version.SourceEntityArn' \
      --aws-account-id $account | cut -f 6 -d \: | cut -f 4 -d \/ 
```

**Comment by fitchtravis** [comment]
That command returns nothing

> $ aws quicksight describe-dashboard --dashboard-id ta-organizational-view --query 'Dashboard.Version.SourceEntityArn' --aws-account-id xxxxxxxxxxxx| cut -f 6 -d \: | cut -f 4 -d \/ 
> (returns an empty line)
$ >

> $ aws quicksight describe-dashboard --dashboard-id ta-organizational-view --query 'Dashboard.Version.SourceEntityArn' --aws-account-id xxxxxxxxxxxx
> "arn:aws:quicksight:us-east-1:223485597511:template/ta-organizational-view"
> $

**Comment by megareez** [comment]
At some point in time there was an issue with dashboards created outside of us-east-1, now the issue is resolved. Redeploy to implement a fix and then the updates via automation will again be available.
