### ISSUE TITLE
hard coded account ID ? and AccessDeniedException

### ISSUE THREAD

**Issue by ManarAbd** [aws-samples/aws-cudos-framework-deployment#561]
The stack is failing for me when it tries to create the dashboard, with the below error. has anyone seen this issue?
Why does it tries to get to a hard coded AWS account ID = default value for cidAccountId in cid/helpers/quicksight/__init__.py ??
I am authenticating to AWS using single sign on, QuickSight and s3 bucket have been provisioned in ap-southeast-2.

Error: waiting for CloudFormation Stack (arn:aws:cloudformation:ap-southeast-2:MYACCOUNTID:stack/Cloud-Intelligence-Dashboards/xx-1693-11ee-xx-xxx) create: failed to create CloudFormation stack, rollback requested (ROLLBACK_COMPLETE): ["The following resource(s) failed to create: [CostIntelligenceDashboard]. Rollback requested by user." "Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (AccessDeniedException) when calling the DescribeTemplate operation: User: arn:aws:sts::MYACCOUNTID:assumed-role/CidExecRole/CidCustomResourceDashboard is not authorized to perform: quicksight:DescribeTemplate on resource: arn:aws:quicksight:us-east-1:223485597511:template/Cost_Intelligence_Dashboard with an explicit deny in a service control policy - Cannot find Cost_Intelligence_Dashboard in account 223485597511.

**Comment by iakov-aws** [comment]
223485597511 is our production account. This is by design that it contains all dashboard template in us-east-1 

please make sure quicksight:DescribeTemplate is whitelisted for us-east-1
