### ISSUE TITLE
ImportError: cannot import name 'get_localzone_name' from 'tzlocal' (/usr/local/lib/python3.7/site-packages/tzlocal/__init__.py)

### ISSUE THREAD

**Issue by work-bw** [aws-samples/aws-cudos-framework-deployment#571]
It looks like the tzlocal module doesn't have get_localzone_name anymore.  It worked a few days ago.  I'm using Cloudshell in us-west-2.  If I'm missing something obvious, sorry.  Thanks.

Brian

[cloudshell-user@ip-10-6-33-99 ~]$ python3 -m ensurepip --upgrade
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmphcswf6is
Requirement already satisfied: setuptools in /usr/lib/python3.7/site-packages (49.1.3)
Requirement already satisfied: pip in ./.local/lib/python3.7/site-packages (23.1.2)
[cloudshell-user@ip-10-6-33-99 ~]$ pip3 install --upgrade cid-cmd
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cid-cmd in ./.local/lib/python3.7/site-packages (0.2.19)
Requirement already satisfied: setuptools in /usr/lib/python3.7/site-packages (from cid-cmd) (49.1.3)
Requirement already satisfied: boto3>=1.26 in /usr/local/lib/python3.7/site-packages (from cid-cmd) (1.26.95)
Requirement already satisfied: Click>=8.0 in ./.local/lib/python3.7/site-packages (from cid-cmd) (8.1.3)
Requirement already satisfied: deepmerge in ./.local/lib/python3.7/site-packages (from cid-cmd) (1.0.1)
Requirement already satisfied: PyYAML in /usr/local/lib64/python3.7/site-packages (from cid-cmd) (5.4.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from cid-cmd) (2.25.1)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/site-packages (from cid-cmd) (3.0)
Requirement already satisfied: six>=1.15 in ./.local/lib/python3.7/site-packages (from cid-cmd) (1.16.0)
Requirement already satisfied: questionary>=1.10 in ./.local/lib/python3.7/site-packages (from cid-cmd) (1.10.0)
Requirement already satisfied: botocore<1.30.0,>=1.29.95 in ./.local/lib/python3.7/site-packages (from boto3>=1.26->cid-cmd) (1.29.116)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.7/site-packages (from boto3>=1.26->cid-cmd) (0.10.0)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/site-packages (from boto3>=1.26->cid-cmd) (0.6.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/site-packages (from Click>=8.0->cid-cmd) (6.1.0)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in ./.local/lib/python3.7/site-packages (from questionary>=1.10->cid-cmd) (3.0.30)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->cid-cmd) (2022.12.7)
Requirement already satisfied: backports.zoneinfo in /usr/local/lib64/python3.7/site-packages (from tzlocal->cid-cmd) (0.2.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.95->boto3>=1.26->cid-cmd) (2.8.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from prompt_toolkit<4.0,>=2.0->questionary>=1.10->cid-cmd) (0.1.9)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata->Click>=8.0->cid-cmd) (3.15.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/site-packages (from importlib-metadata->Click>=8.0->cid-cmd) (4.4.0)
[cloudshell-user@ip-10-6-33-99 ~]$ cid-cmd -vv --help
Traceback (most recent call last):
  File "/home/cloudshell-user/.local/bin/cid-cmd", line 5, in <module>
    from cid.cli import main
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/cli.py", line 5, in <module>
    from cid.common import Cid
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/common.py", line 27, in <module>
    from cid.helpers.account_map import AccountMap
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/__init__.py", line 5, in <module>
    from cid.helpers.quicksight import QuickSight, Dashboard, Dataset, Datasource, Template
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/quicksight/__init__.py", line 13, in <module>
    from cid.helpers import diff, timezone, randtime
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/cid/helpers/timezone.py", line 7, in <module>
    from tzlocal import get_localzone_name
ImportError: cannot import name 'get_localzone_name' from 'tzlocal' (/usr/local/lib/python3.7/site-packages/tzlocal/__init__.py)
[cloudshell-user@ip-10-6-33-99 ~]$

**Comment by iakov-aws** [comment]
Hello can you do:
```
pip3 freeze |grep tzlocal
```

**Comment by iakov-aws** [comment]
please use 

pip3 install -U tzlocal

as a workaround

**Comment by work-bw** [comment]
pip3 install -U tzlocal worked, thanks.
