### ISSUE TITLE
Cid-cmd update fails with timezone ValueError

### ISSUE THREAD

**Issue by pkujala** [aws-samples/aws-cudos-framework-deployment#574]
Trying to run `cid-cmd update` for computer optimizer dashboard using CloudShell at eu-west-1 where our CID Quicksight installation is. However, the update fails with error msg ``ValueError: Invalid `default` value passed. The value (`Europe/Dublin`) does not exist in the set of choices. Please make sure the default value is one of the available choices.``

Relates somehow to Quicksight dataset's refresh scheduling? I noticed that automatic daily refreshes for dataset `compute_optimizer_all_options` got broken after cid-cmd update attempt. In Quicksight's dataset refresh tab there's now failed refreshes their error type being `SQL_EXCEPTION` and error details:

`[ErrorCode: INTERNAL_ERROR_QUERY_ENGINE] Amazon Athena experienced an internal error while executing this query. Please contact AWS support for further assistance. You will not be charged for this query. We apologize for the inconvenience. [Execution ID: ae73cf16-a53c-4095-b881-943cbba77c02]`

Attached anonymized cid-cmd debug log.
[cid.log](https://github.com/aws-samples/aws-cudos-framework-deployment/files/11965515/cid.log)

**Comment by iakov-aws** [comment]
Checking

**Comment by iakov-aws** [comment]
Please can you update the tool. This was a regression fixed in the latest release  
```
pip3 install -U cid-cmd
```

**Comment by pkujala** [comment]
Can confirm dashboard update worked with new cid-cmd release, thank you 👍

**Comment by iakov-aws** [comment]
Thank you!
