### ISSUE TITLE
No value returned on Primary Tag on Compute Optimiser Dashboard

### ISSUE THREAD

**Issue by efernandes-dev-ops** [aws-samples/aws-cudos-framework-deployment#576]
Hi,

We've update to the latest version of the Compute Optimiser Dashboard v2.0.1

We set "service" as primary tag and "owner" as secondary tag. For some reason we don't seem to get any values being returned on the primary tag and we just get NULL value in the dropdown.

![image](https://github.com/aws-samples/aws-cudos-framework-deployment/assets/22025436/1c7e43dc-c25d-42b0-9d1a-4593524536dd)

Not sure if anyone can help us debug this. 

Thanks

**Comment by iakov-aws** [comment]
Please let us know if still an issue
