### ISSUE TITLE
Anomaly Detection issue in  Cost_Summary tab in CID dashboard

### ISSUE THREAD

**Issue by nirooptgd** [aws-samples/aws-cudos-framework-deployment#583]
Hi Team,
I couldn't able to see the data in Cost_summary tab and Anomaly detection. I have tried configure anomaly time period to Week and Month as well, Its keep on showing like attached image. I have last 24 Months data in my dataset.
Can anyone help , is I am doing anything wrong in the process. It would be great if some one help to rid of this issue.

![image](https://github.com/aws-samples/aws-cudos-framework-deployment/assets/94053316/21738f77-134d-4eb1-85a1-d0b01a577e94)

**Comment by yprikhodko** [comment]
Hi [nirooptgd](https://github.com/nirooptgd),
I recommend to use our new [Cost Anomaly Dashboard](https://catalog.workshops.aws/awscid/en-US/dashboards/advanced/cost-anomaly) which uses results of  https://aws.amazon.com/aws-cost-management/aws-cost-anomaly-detection/ feature of cost explorer and more accurate for cost data then general anomaly models used in QuickSight.
