### ISSUE TITLE
KPI Datasets fail to Refresh

### ISSUE THREAD

**Issue by AdamDivall** [aws-samples/aws-cudos-framework-deployment#585]
Hi There,

I've deployed the CID, CUDOS, & KPI Dashboards into our account but once I run the SQL Script as directed to do the Account Mapping under Option 3 (https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/code/0_view0/).  This effectively prevents the kpi_* datasets from refreshing with the error being:

Error type:
SQL_EXCEPTION [Learn more](https://docs.aws.amazon.com/console/quicksight/errors)
This is a general SQL error. This can be caused by query timeouts, resource constraints, unexpected DDL alterations before or during a query, and other database errors. Check your database settings and your query, and try again.
Error details:
INVALID_VIEW: line 3:6: Failed analyzing stored view 'awsdatacatalog.cid_cur.kpi_tracker': line 144:6: View 'awsdatacatalog.cid_cur.kpi_instance_all' is stale or in invalid state: column [account_name] of type varchar projected from query view at position 35 has a different name from column [parent_account_id] of type varchar stored in view definition [Execution ID: cb43c9a9-0e20-4a1c-ad35-ca533a755aae]

Can you please advise?

Many Thanks

**Comment by iakov-aws** [comment]
Please check this FAQ
https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/faq/#i-am-getting-the-error-sql_exception-view-is-stale-it-must-be-re-created---what-do-i-do
