### ISSUE TITLE
Typo 'Ressource' in cid-cfn.yaml

### ISSUE THREAD

**Issue by nchicong** [aws-samples/aws-cudos-framework-deployment#612]
There is extra 's' in Ressources which appears 7 times in https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/cfn-templates/cid-cfn.yml

E.g: CustomRessourceFunctionInit

There are other places I can see "ressouce" as in "ressouce_details". Not sure if it's intended.

**Comment by iakov-aws** [comment]
Fixed here https://github.com/aws-samples/aws-cudos-framework-deployment/pull/623 will be merged for the next version release

**Comment by iakov-aws** [comment]
Thanks for feedback
