### ISSUE TITLE
Inconsistent formatting on the time axis of daily spend visuals on the Databases sheet of CUDOS dashboard

### ISSUE THREAD

**Issue by sdwood992** [aws-samples/aws-cudos-framework-deployment#619]
On the Databases sheet of the CUDOS dashboard the 'Daily Cost by Instance Family|Instance Type|Processor Type for All' chart has the X time axis formatted to  Mth yyyy, for example Aug 2023. This means that when reading the chart it is quite difficult to know which day each bar relates to.

The 'Daily Storage Cost for Amazon Relational Database Service' visual has it nicely formatted as Mth d, yyyy, for example Aug 29, 2023. It would be very helpful if all the daily spend charts specified the day on the time axis and they are consistent in their formatting.

Also or note the 'Database Daily Elasticity in Normalized Hours by Purchase Option for All' visual on the Databases sheet has the X time axis formatted as Mth d, for example Aug 29.
![daily-cost-by-X-for-all](https://github.com/aws-samples/aws-cudos-framework-deployment/assets/11332827/993dd29f-5ca6-4fee-bdf2-bb9c6d92e96a)

**Comment by yprikhodko** [comment]
Fixed in CUDOS v5 - https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/changes/CHANGELOG-cudos.md#cudos---500
