### ISSUE TITLE
RDS Aurora I/O-Optimized not showing correctly in the  "Daily Storage Cost for Amazon Relational Database Service" view in CUDOS

### ISSUE THREAD

**Issue by danbaril-aws** [aws-samples/aws-cudos-framework-deployment#637]
When customers enable Aurora I/O-Optimized, the "Daily Storage Cost for Amazon Relational Database Service" replaces **_RDS  Aurora Storage_** with **_RDS Magnetic Storage_**.

To fix the issue, a new line should be added in the calculated field **Databases Storage Type**
Below an example:
```
{product_code} = 'AmazonRDS' and locate({usage_type}, 'Aurora:IO-OptimizedStorageUsage')> 0,
    'RDS Aurora I/O Optimized Storage',
```

Please note that the compute usage type also changes to **InstanceUsageIOOptimized:<instance_type>** and it could affect other visuals.

**Comment by yprikhodko** [comment]
will be added in the next CUDOS release

**Comment by yprikhodko** [comment]
Released in CUDOS v5 - https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/changes/CHANGELOG-cudos.md#cudos---500
