### ISSUE TITLE
Support for Dashboard view for multiple accounts not part of an organization

### ISSUE THREAD

**Issue by shreedharn** [aws-samples/aws-cudos-framework-deployment#66]
Does this CUDOs framework support dashboard view of multiple accounts that are not part of an organization / a payer.

For example: Let us say:
- Account B has Account A as a Payer account 
- Account D has Account C as a Payer account. 

1. Can the cudos dashboard view show accounts from both Account B and Account D?
2. If so, is there any documentation for deploying such configuration? As per our understanding CUR usually have billing information about the account from which CUR is generated (and sub accounts if the CUR is generated from the payer account).  The question is how the single QuickSight dashboard view can be configured to display multi account information when the dataset come from different CUR (given that Account B and Account D belong to different Payer).

**Comment by yprikhodko** [comment]
This is possible via s3 bucket replication from multiple payer accounts to single bucket. You can follow this doc https://cudos.workshop.aws/prerequisites_multipayer.html to set it up
