### ISSUE TITLE
InventoryCollectorModule - nested stack issue capitalization change breaks CFN OptimizationDataCollectionStack stack update

### ISSUE THREAD

**Issue by bwollermann** [aws-samples/aws-cudos-framework-deployment#669]
I have an older version of the OptimizationDataCollectionStack template installed that does not have support for the anomaly data collection module.  I want to add that nested stack so that I can install the Cost Anomaly dashboard.  However, in the new template LambdaRole - logical ID of the "AWS::IAM::Role" resource has changed the name from a capital I to a lower case i and the stack update fails and rolls back.  Since the nested stacks refer to URL templates that AWS controls I can't fix the problem.  Is there a work-around you can suggest?

I'm nervous about uninstalling OptimizationDataCollectionStack and all the nested stacks because I don't want to lose all my Athena tables that have been gathering data for over a year.  Please help.  Thanks!

Brian

**Comment by esc1144** [comment]
Hi Brian,
Thank you for bringing this to our attention. We are looking into it now. In the meantime, please let us know if you are an AWS Enterprise Support customer and have a TAM and account team that we can engage as well to further assist you.

**Comment by bwollermann** [comment]
Yes, we are an Enterprise customer.  I also opened a ticket with the CloudFormation team yesterday on this issue and they suggested posting here.  Here is the info:

AWS ticket #= 14259208191
Our AWS TAM= Erwin, John <jmerwin@amazon.com>

**Comment by esc1144** [comment]
Great, thank you. I will reach out to your TAM and we can troubleshoot more directly with you.

**Comment by iakov-aws** [comment]
Please comment or reopen if still an issue
