### ISSUE TITLE
Support for Dashboard view for multiple accounts from CUR generated at the respective account level

### ISSUE THREAD

**Issue by shreedharn** [aws-samples/aws-cudos-framework-deployment#67]
Does this CUDOs framework support dashboard view of multiple accounts that are part of an organization but with CUR generated at the individual account level (and not at the payer level)?

For example: Let us say:

- Account B has Account K as a Payer account
- Account D has Account K as a Payer account.

CUR is generated individually at Account B and Account D (not at payer account K as there is no permission for the user to generate CUR at Account K level)

1. Can the cudos dashboard view show accounts from both Account B and Account D?
2. If so, is there any documentation for deploying such configuration? As per our understanding CUR usually have billing information about the account from which CUR is generated (and sub accounts if the CUR is generated from the payer account). The question is how the single QuickSight dashboard view can be configured to display multi account information when the dataset come from different CUR from Account B and Account D (and not from Account K)

**Comment by darken99** [comment]
Yes, this is covered in [workshop](https://cudos.workshop.aws/prerequisites_multipayer.html)

**Comment by shreedharn** [comment]
Is the dashboard features listed in the following links same:
1.  https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/
2.  https://cudos.workshop.aws/workshop.html

If not, which lab does this GitHub repo correspond?
