### ISSUE TITLE
cid-cmd cannot update to CUDOS v5.0.0 

### ISSUE THREAD

**Issue by kodyabbott** [aws-samples/aws-cudos-framework-deployment#704]
Will cid-cmd be updated to allow us to update from CUDOS - 4.79 to CUDOS v5.0.0?
 
I do see that the change log shows deprecated for v4 - https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/changes/CHANGELOG-cudos.md
 
When using cid-cmd status this is what I see showing that 4.79 is the latest and status is up to date:
 
```❯ cid-cmd status
CLOUD INTELLIGENCE DASHBOARDS (CID) CLI 0.2.39 Beta
 
Loading plugins...
      Core loaded
 
 
Checking AWS environment...
      profile name: default
      accountId: 123456789123
      AWS userId: [redacted]
      Region: us-east-1
 
 
Discovering deployed dashboards...  [####################################]  100%  "CUDOS Dashboard" (cudos)
 
? [dashboard-id] Please select dashboard from the list: CUDOS Dashboard (arn:aws:quicksight:us-east-1:123456789123:dashboard/cud
os, healthy, up to date) This version of the CUDOS deprecated. Deploy CUDOS Dashboard v5 instead
 
Dashboard status:
  Id:        cudos
  Name:      CUDOS Dashboard
  Health:    healthy
  Status:    up to date
  Version:   v4.79.0 (latest)
  VersionId: 202 (latest)
```
 
`cid-cmd update` also shows “No updates available”.

**Comment by yprikhodko** [comment]
Hi Kody,
 
You need to update cid-cmd first and then you’ll be able to deploy CUDOS v5 with it. It won’t be in-place update but a new dashboard which you will have deployed. Here are some more details about deployment of CUDOS v5 - https://catalog.workshops.aws/awscid/en-US/faqs#how-to-update-to-cudos-v5-if-i-have-previous-version-of-cudos-installed
