### ISSUE TITLE
DataTransfer Cost Analysis Dashboard - data_transfer_view permissions denied

### ISSUE THREAD

**Issue by qmg-drettie** [aws-samples/aws-cudos-framework-deployment#705]
After running `cid-cmd deploy --dashboard-id datatransfer-cost-analysis-dashboard` as per the steps in the [install guide](https://catalog.workshops.aws/awscid/en-US/dashboards/additional/data-transfer) QuickSight is unable to perform an initial load of the dataset with an error. -

```
Error type:
PERMISSION_DENIED [Learn more](https://docs.aws.amazon.com/console/quicksight/errors)
User does not have permission to access the above project
Error details:

Insufficient permissions to execute the query. User: arn:aws:sts::123456789000:assumed-role/CidQuickSightDataSourceRole/QuickSight-RoleSession-1702742468509 is not authorized to perform: glue:GetPartition on resource: arn:aws:glue:eu-west-2:123456789000:catalog because no identity-based policy allows the glue:GetPartition action [Execution ID: 544ae0e7-2b96-4e8f-8698-f02b804d9165]
```

The `AthenaAccess` policy attached to the `QuickSightDataSourceRole` seems to be missing the `glue:GetPartition` action

**Comment by iakov-aws** [comment]
Hi [David](https://github.com/qmg-drettie), Thanks for raising this and proposing the fix. Checking.

**Comment by iakov-aws** [comment]
This make sense. Not sure when QS uses `glue:GetPartition` vs `glue:GetPartitions`, so make sense to include both. Thanks for the contribution! Merged.
