### ISSUE TITLE
Some data transfer & networking visuals show No Data in CUDOS v5

### ISSUE THREAD

**Issue by hansarh** [aws-samples/aws-cudos-framework-deployment#719]
I have deployed the CUDOS v5 dashboard using cid-cmd and mostly it seems to be working with the exeption of some visuals not showing data in the `Data Transfer & Networking` tab. `Data Transfer Top 15 Resources Last 30 Days`, `Network Resources Detailed View Last 30 Days (Top 10)` and `Idle Resources with no traffic Last 30 Days` to mention a few. The corresponding visuals are working in the v4 version we have still running.

All datasets are being refreshed daily without errors. What can I do to troubleshoot this?

![image](https://github.com/aws-samples/aws-cudos-framework-deployment/assets/6917956/aa74b463-d745-4031-9376-716a9e56270e)

**Comment by iakov-aws** [comment]
please check status of the dashboard and datasets. you can do that with this command cid-cli (https://github.com/aws-samples/aws-cudos-framework-deployment/)

`cid-cmd status`

**Comment by hansarh** [comment]
not too much help to get from that command: 
![image](https://github.com/aws-samples/aws-cudos-framework-deployment/assets/6917956/0fdb22a9-665e-4b66-ac12-1b79daaf5bc3)

**Comment by iakov-aws** [comment]
can u select the dashboard for more details?

**Comment by hansarh** [comment]
![image](https://github.com/aws-samples/aws-cudos-framework-deployment/assets/6917956/c84eaffc-890d-408c-894d-b1d0cf2045e0)

**Comment by iakov-aws** [comment]
I see hourly and resource views re not updated since 70 days. Can you check and set the schedule for full refresh of these datasets?
