### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by jinman** [aws-samples/aws-cudos-framework-deployment#722]
Hi team,

We are trying to leverage the CUDOS dashboards but we dont have all the data for all the services in our AWS account. Can you please point us to the sample data that is currently being used that we can possibly use to visualize the data? Is it possible to get access to sample CUR data that is available in the public demo?

Jin

**Comment by iakov-aws** [comment]
Hello 


We do not provide samples of data. 

You can have our public demo to see how it would look like https://cid.workshops.aws.dev/demo?dashboard=cudos


If you are an Enterprise Support customer you can contact your TAM for a personalized presentation.

**Comment by jinman** [comment]
@iakov-aws thanks for the reply.

Do you have Faker data script that we can potentially generate dummy data for all the services to make the dashboards alive?
