### ISSUE TITLE
Support for Trusted Advisor Organization dashboard in a different region other than Quicksight identity region

### ISSUE THREAD

**Issue by shreedharn-cbm** [aws-samples/aws-cudos-framework-deployment#73]
Cudos and Trends dashboard supports deployment to regions that is different from QuickSight Identify region. But Trusted Advisor Organization dashboard does not have such a configuration.

Following error is displayed when the target region is selected for dashboard deployment:
An error occurred (AccessDeniedException) when calling the ListUsers operation: Operation is being called from endpoint <target_region>, but your identity region is <identity_region>

**Comment by darken99** [comment]
Please try new automation (pip package)
