### ISSUE TITLE
[BUG] - Automated and manual deployment of "summary_view" fails - continued

### ISSUE THREAD

**Issue by mlewis7127** [aws-samples/aws-cudos-framework-deployment#74]
This is similar to the previous bug that has been raised around 'product_database_engine' not being resolved, which could be resolved by launching an RDS instance for an hour

I also get the following errors after doing this and waiting for the next CUR report to be run:

com.facebook.presto.v217.sql.analyzer.SemanticException: line 43:4: Column 'product_tenancy' cannot be resolved
com.facebook.presto.v217.sql.analyzer.SemanticException: line 45:4: Column 'product_processor_features' cannot be resolved

I solely run services such as API Gateway, Lambda, DynamoDB, QLDB and Kinesis in this account, so is it just a case of running an ec2 instance for an hour, or are there others services required to appear in the CUR report

**Comment by mlewis7127** [comment]
Running an ec2 instance and waiting for next report to be delivered did the trick. It would be useful if a list of services that need to be run, even for an hour, such as EC2 and RDS, where included in the README

**Comment by darken99** [comment]
@megareez please check if we can add more info into docs
