### ISSUE TITLE
Tag 0.2.47 references invalid policy ARNs

### ISSUE THREAD

**Issue by jhenry82** [aws-samples/aws-cudos-framework-deployment#763]
I coincidentally tried to deploy the CID dashboards today right after tag 0.2.47 was cut. The CFN stack is failing to deploy with several errors like this:

```
Resource handler returned message: "ARN arn:aws:iam:policy/service-role/AWSLambdaBasicExecutionRole is not valid. (Service: Iam, Status Code: 400, Request ID: 4ca4ea73-9841-4723-949d-a86fe378e1a2)" (RequestToken: aa51dbe6-e6d4-e41d-9872-cf94fafd89b8, HandlerErrorCode: InvalidRequest)
```

The stack is referencing an invalid ARN in several places. It should be using `arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole`.

The stack cannot currently be deployed at all due to this error.

**Comment by jhenry82** [comment]
Looks like this was changed in https://github.com/aws-samples/aws-cudos-framework-deployment/pull/759 by @iakov-aws

**Comment by iakov-aws** [comment]
yes. can you retry?

**Comment by iakov-aws** [comment]
Fixed in https://github.com/aws-samples/aws-cudos-framework-deployment/pull/762 sorry for inconvinience
