### ISSUE TITLE
Incorrect Account Name in aws_accounts

### ISSUE THREAD

**Issue by netacea-philh** [aws-samples/aws-cudos-framework-deployment#764]
I was looking through the CUDOS v5 dashboard and noticed on the Executive: RI/SP Summary tab, there's an Account Map visual.

The Account Map has two fields shown, Account ID and Account Name, but when rendered it shows the Account ID for both fields.

Looking through Athena, it looks like this comes from `cid_cur.account_map` which shows the `account_name` field to be the same as the `account_id`.    Does this have something to do with this line?  https://github.com/aws-samples/aws-cudos-framework-deployment/blame/7c8fe605c07cfb2ce07d22e39d588b83e1bab196/cid/helpers/account_map.py#L297

Thanks!

**Comment by iakov-aws** [comment]
Hello, this is expected. Please check this guide  https://catalog.workshops.aws/awscid/en-US/dashboards/foundational/cudos-cid-kpi/add-accounts

**Comment by netacea-philh** [comment]
Thanks!
