### ISSUE TITLE
Wrong config in readme.md file

### ISSUE THREAD

**Issue by guelah75** [aws-samples/aws-cudos-framework-deployment#8]
To refresh AWS Trusted Advisor Organizational View data (we recommend to perform this step at least once per month):

    Create AWS Trusted Advisor Organizational View report

    Download AWS Trusted Advisor Organizational View report and unzip it

    Upload report unzipped folder to s3://{bucket}/reports

    Run following script:

    ./shell-script/tao.sh --action=update

** I believe the command should be ./shell-script/tao.sh --action=refresh-data

**Comment by yprikhodko** [comment]
Amended readme.md
