### ISSUE TITLE
Work folders are not properly being ignored by git

### ISSUE THREAD

**Issue by tarfahachem-nbcuni** [aws-samples/aws-cudos-framework-deployment#82]
In .gitignore the line

*/work/

does not instruct git to ignore work folders. The line should be

work/

**Comment by kentnsw** [comment]
FYI, the `*/work/` works for me

**Comment by darken99** [comment]
Can provide any details on what exactly is not working as expected?

**Comment by tarfahachem-nbcuni** [comment]
Please examine the shell output in the two files I attached. The work folder is not in the root folder nor did I run the scripts that generated it from the root folder. The issue is that git, with the original gitignore file, wants to add and commit the nested work folders.

This shows clearly that it git sees the folder and its files when it should ignore them:

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	cudos/shell-script/work/

~/o/p/a/aws_cudos_framework ❯❯❯ git add .                                                                                gitignore-patch ✚ ✱ ◼
~/o/p/a/aws_cudos_framework ❯❯❯ git status                                                                                   gitignore-patch ✚
On branch gitignore-patch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   .gitignore
	new file:   cudos/shell-script/work/017894252151/account_map_view.sql
	new file:   cudos/shell-script/work/017894252151/account_map_view.sql.bu
	new file:   cudos/shell-script/work/017894252151/queries/athena_table_names.sql

**Comment by darken99** [comment]
> Please examine the shell output in the two files I attached. The work folder is not in the root folder nor did I run the scripts that generated it from the root folder. The issue is that git, with the original gitignore file, wants to add and commit the nested work folders.
> 
> This shows clearly that it git sees the folder and its files when it should ignore them:
> 
> Untracked files: (use "git add ..." to include in what will be committed) cudos/shell-script/work/
> 
> ~/o/p/a/aws_cudos_framework ❯❯❯ git add . gitignore-patch ✚ ✱ ◼ ~/o/p/a/aws_cudos_framework ❯❯❯ git status gitignore-patch ✚ On branch gitignore-patch Changes to be committed: (use "git restore --staged ..." to unstage) modified: .gitignore new file: cudos/shell-script/work/017894252151/account_map_view.sql new file: cudos/shell-script/work/017894252151/account_map_view.sql.bu new file: cudos/shell-script/work/017894252151/queries/athena_table_names.sql

Can't reproduce what you observe:
```
 ~/tmp  git clone https://github.com/aws-samples/aws-cudos-framework-deployment
Cloning into 'aws-cudos-framework-deployment'...
remote: Enumerating objects: 384, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 384 (delta 97), reused 23 (delta 14), pack-reused 220
Receiving objects: 100% (384/384), 126.77 KiB | 1.39 MiB/s, done.
Resolving deltas: 100% (198/198), done.
 ~/tmp  cd aws-cudos-framework-deployment
 ~/tmp/aws-cudos-framework-deployment   main  mkdir -p {cudos,tao,trends}/work/595346786485/
 ~/tmp/aws-cudos-framework-deployment   main  mkdir -p /work/595346786485/
mkdir: /work/595346786485/: Read-only file system
 ✘  ~/tmp/aws-cudos-framework-deployment   main  mkdir -p work/595346786485/
 ~/tmp/aws-cudos-framework-deployment   main  git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```
