### ISSUE TITLE
Cloudformation deployment error in eu-west-3

### ISSUE THREAD

**Issue by buknon** [aws-samples/aws-cudos-framework-deployment#842]
I try deploy cudo with cloudformation in eu-west-3. I get this error: 

`Received response status [FAILED] from custom resource. Message returned: Failed Create cost_intelligence_dashboard with exception: Please set parameter quicksight-datasource-role. Unable to request user in environment={'os': 'Linux', 'shell': 'lambda', 'terminal': 'lambda'}.`

After a quick look on template I see this condition:

`  NeedDatasource: !Not [ !Equals [ !Ref "AWS::Region", "eu-west-3" ] ] # In eu-west-3 CFN QS Dataset resource is not available yet.`

Does this mean that we cannot deploy the dashboards in eu-west-3  or do we have to do a special step to deploy it?

**Comment by iakov-aws** [comment]
Yes there is a workaround that causes issues now. Removing it here https://github.com/aws-samples/aws-cudos-framework-deployment/pull/849

**Comment by buknon** [comment]
Ok thanks @iakov-aws ! We will test it

**Comment by iakov-aws** [comment]
Fixed in the main template
