### ISSUE TITLE
Creating health_events_view fails in cid-cmd due to SQL query issue

### ISSUE THREAD

**Issue by frankrosano** [aws-samples/aws-cudos-framework-deployment#855]
I was attempting to deploy the new Health Events Dashboard with cid-cmd in my environment however the automated Athena view creation fails due to a syntax issue with the query. Error:

`CRITICAL - InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:27: mismatched input '-'. Expecting: 'AS', 'COMMENT', 'SECURITY', 'WITH'`

Screenshot of error:

<img width="1520" alt="Screenshot 2024-06-24 at 11 54 27 AM" src="https://github.com/aws-samples/aws-cudos-framework-deployment/assets/822940/31faef1d-b2d8-404b-9874-6f4aacbd76c5">

Attempting to run the query manually in Athena results in the same error:

<img width="1228" alt="Screenshot 2024-06-24 at 11 52 49 AM" src="https://github.com/aws-samples/aws-cudos-framework-deployment/assets/822940/c65408e4-8775-468f-9d66-61e521ae3ab8">

**Comment by iakov-aws** [comment]
Thanks for the reporting and contribution! Merged. 
Will be released soon.
