### ISSUE TITLE
New modules default values

### ISSUE THREAD

**Issue by joegajeckyj** [aws-samples/aws-cudos-framework-deployment#863]
Hi,

Please can I request that you set default values to "no" for any new modules and updates that include new modules?

I am utilising the templates as a stackset and when you introduce new modules they are causing it to fail as I nee to pass the parameters in.

Cheers

**Comment by iakov-aws** [comment]
checking

**Comment by iakov-aws** [comment]
do you have some specific exampe? is it about cid-cfn or data collection?

**Comment by joegajeckyj** [comment]
'''
    {
        "ParameterKey": "pIncludeHealthEventsModule",
        "ParameterValue": "no"
    },
    {
        "ParameterKey": "pIncludeAWSFeedsModule",
        "ParameterValue": "no"
    }
'''

**Comment by joegajeckyj** [comment]
"https://${pCFNSourceBucket}.s3.amazonaws.com/cfn/data-collection/deploy-data-collection.yaml"

**Comment by joegajeckyj** [comment]
"https://${pCFNSourceBucket}.s3.amazonaws.com/cfn/data-collection/deploy-data-read-permissions.yaml"

IncludeHealthEventsModule

**Comment by iakov-aws** [comment]
ok i see it is in https://github.com/awslabs/cid-framework/ checking.

**Comment by iakov-aws** [comment]
https://github.com/awslabs/cid-framework/pull/152/files

**Comment by iakov-aws** [comment]
super curious what kind of automation you have in place

**Comment by joegajeckyj** [comment]
I have integrated with CfCT

**Comment by iakov-aws** [comment]
CfCT ?

**Comment by joegajeckyj** [comment]
Customizations for Control Tower

**Comment by iakov-aws** [comment]
Close as fixed. thanks for your feedback
