### ISSUE TITLE
Readme usage instructions are incomplete/inaccurate

### ISSUE THREAD

**Issue by davidtudorjohn** [aws-samples/aws-cudos-framework-deployment#906]
We have implemented these Terraform modules to deploy our dashboards. While working on this I had a hard time following the usage instructions.

Here are a few issues I found:

1. In the [Before you start](https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/terraform-modules/README.md) section, it says "Complete the prerequisites for respective dashboard". When clicking the link (e.g. for CUDOS) it simply takes me to the Cost & Usage Report page. There is nothing to actually complete in terms of a prerequisite.
2. In the [Before you start](https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/terraform-modules/README.md) section, it says "Specifying a Query Result Location Using a Workgroup". This was already set after deploying the modules. If in some cases it is required, letting users know which bucket would be beneficial as it is unclear.
3. In this [Readme](https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/terraform-modules/README.md#example-usage-1) you could simply add the S3 bucket resource and reference it in the module to give a more comprehensive usage example

**Comment by iakov-aws** [comment]
@sean-nixon  can you check?

**Comment by sean-nixon** [comment]
@davidtudorjohn Thanks for your feedback. I've created a PR with some updates to try to address some of those areas of confusion. Note that for your third point, I have left the S3 bucket creation out purposefully to keep the example focused. Provisioning a secure S3 bucket according to best practices can be a lot of code and everyone's environment and standards are different.

**Comment by iakov-aws** [comment]
https://github.com/aws-samples/aws-cudos-framework-deployment/pull/908 is merged. Great Work @sean-nixon 

@davidtudorjohn thank you for the feedback! Please do not hesitate to share more!
