### ISSUE TITLE
Changing cid CUR data export from hourly to daily

### ISSUE THREAD

**Issue by work-bw** [aws-samples/aws-cudos-framework-deployment#912]
Can you tell me what would be the impact to the dashboards if I changed the cid CUR data export from hourly to daily?  I have a field that I need in a view where the refresh takes over an hour.  The refresh always fails and the Athena team looked at the issue and is recommending me to adjust the frequency of the data export.  The Execution IDs show that the data export is modifying the data while the refresh is occurring.  .  I can provide you the case ID in a non-public forum if that is helpful or work through my TAM.  Thanks.

Brian

**Comment by iakov-aws** [comment]
Hello Brain, 
You can switch CUR aggregation to daily, this way you will have one record per day and not per hour. It will make your CUR almost 24 times less in terms of storage, but you will not see any hour patterns and your  compute consumption chart would looks like that:
<img width="1524" alt="image" src="https://github.com/user-attachments/assets/1f6804f5-3c5d-4793-9110-a16c66f273be">


Please note that hourly vs daily is a [Time granularity](https://docs.aws.amazon.com/cur/latest/userguide/cur-create.html) of CUR and not schedule. The CUR data will be still delivered around 3 times a day. 

If the refresh fails on timeout please [check this faq](https://catalog.workshops.aws/awscid/en-US/faqs#i'm-getting-an-error-in-quicksight-that-is-saying-athena-timed-out.) first and if it does not help you can adjust granularity and /or contact your TAM to set up a call with CID team for more personalized recommendations.

**Comment by iakov-aws** [comment]
I will close the issue but feel free to update or followup here or via you TAM.
