### ISSUE TITLE
Visuals show "No data"

### ISSUE THREAD

**Issue by engrun** [aws-samples/aws-cudos-framework-deployment#98]
I have the following setup

* CUR report exported to management account s3 bucket
* CUR report is replicated to monitoring account s3 bucket
* QuickSight Enterprise is setup in monitoring account
* Followed the automatic setup scrips for cudos dashboards and made sure all prerequisites are done (standard prerequisite, not the multi-payer)

After this, the dashboards should be ready. 

However, when opening up the dashboard for the first time, a LOT of the visuals showed "No data". 
So I figured I should leave it for a few days. 
However, after 6 days, the visuals still show "No data"

For a lot of the visuals  guess this is normal (all visuals for previous months). 
However, for other visuals, e.g. 
* data transfer
* Top 10 spending accounts by total cost. (multiple of these)
* All the Cost by purchase option 

the dashboard still shows "No data"

It is not easy to debug this, but I have
* queried athena to verify I get data
* open up the QuickSight datasets for verify I get data 

Also, I cannot find the dashboard template (arn:aws:quicksight:us-east-1:223485597511:template/cudos_dashboard_v3), which (maybe?) could have helped me figure out how the visuals are configured. 

*Maybe related*
Yesterday I noticed 100+ ThrottlingException/RateExceeded for the Athena GetQueryExecution api call. 
After each reload of the dashboard this number increased with approx 5-10

**Comment by megareez** [comment]
if the CUR is new that is expected as the data is mostly visualised for the previous 30 days/couple of month. You might get a CUR backfill if you file a request via support center
