### ISSUE TITLE
Increment refresh for QuickSight CID datasets

### ISSUE THREAD

**Issue by sophie-warner-annalise-ai** [aws-samples/aws-cudos-framework-deployment#987]
All datasets created in https://github.com/aws-samples/aws-cudos-framework-deployment/tree/main/terraform-modules/cid-dashboards use full refresh. Full refresh can take hours for large datasets. If datasets have a date column you can use incremental refresh instead. Then they'll only ingest new data instead of the whole dataset everytime a refresh happens, reducing downtime.

**Comment by iakov-aws** [comment]
Hello @sophie-warner-annalise-ai 

>###### [Can we use Incremental Refresh for CUR Datasets?](https://catalog.workshops.aws/awscid/en-US/faqs#can-we-use-incremental-refresh-for-cur-datasets)
>No. We must use Full Refresh and not Incremental for all QuickSight Datasets that involve CUR. After Finalization of Invoicing (typically in the middle of month) CUR will update data and override files for previous month. Incremental Refresh option cannot not support this.

 
Otherwise it would be really great.
