### ISSUE TITLE
CUR export bucket s3 policy

### ISSUE THREAD

**Issue by vivien-ramahandry-fox** [aws-samples/aws-cudos-framework-deployment#989]
Since the this #825 and also this one #879 AWS service billing reports can't upload new CUR on my bucket

**Comment by iakov-aws** [comment]
Thanks for reporting this. 

Does this work if you remove the condition from the statement?

**Comment by vivien-ramahandry-fox** [comment]
Hello @iakov-aws I deleted yesterday and It works this morning
and before I have this
![image](https://github.com/user-attachments/assets/0951c73d-26db-4e24-abab-194fefb4298b)

**Comment by iakov-aws** [comment]
Thanks 

Normally we follow documentation 

https://docs.aws.amazon.com/cur/latest/userguide/cur-s3.html


Was will check internally and get back to you.

**Comment by iakov-aws** [comment]
Can you confirm you just deleted account restriction?

https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/cfn-templates/cur-aggregation.yaml

**Comment by vivien-ramahandry-fox** [comment]
I deleted the 2 conditions here
https://github.com/aws-samples/aws-cudos-framework-deployment/blob/main/terraform-modules/cur-setup-destination/main.tf#L186
because I'm using terraform module for cur part and not cloudformation

**Comment by iakov-aws** [comment]
Ok I see. We updated cloud formation but not TF. 

Do you want to suggest a PR just leaving account condition. If not we will do it in the following days. 

Thank again for raising and your analysis!

**Comment by vramahandry** [comment]
Yeah sure I will create the PR with my personal account and close the other one but I think you can add the region us-east-1 on the condition. I will test it and let you know

**Comment by vramahandry** [comment]
you can close this #990

**Comment by iakov-aws** [comment]
Thanks for update and your contribution!
