### ISSUE TITLE
CORA dashboard - Cannot create duplicate export name

### ISSUE THREAD

**Issue by Waqiah** [aws-samples/aws-cudos-framework-deployment#995]
Hello Team, 

When following the three steps mentioned in the below documentation to deploy CORA dashboard:
https://catalog.workshops.aws/awscid/en-US/data-exports#deployment

Step 1 is successful but in step 2 the stack (CID-DataExports-Source) failed to deploy in the management account with error, “Received response status [FAILED] from custom resource. Message returned: An error occurred (ValidationException) when calling the CreateExport operation: Cannot create duplicate export name.” 

What can I do or where do I go to, to confirm if I have an existing data export with the same name? If it does exist, do I delete this and then retry the deployment?

**Comment by iakov-aws** [comment]
Data exports stack can be just one. You can have multiple data exports there. 


If you have a usecase for multiple stacks please let me know.

**Comment by iakov-aws** [comment]
If you already have CID-DataExports-Source you can just enable COH report there by updating the stack

**Comment by iakov-aws** [comment]
Closing. Please comment if still an issue.
